### ISSUE TITLE
Mask batch

### ISSUE THREAD

**Issue by AbyszOne** [WASasquatch/was-node-suite-comfyui#10]
Is there any way to use mask in the batch? Also, is image to latent mask the node to use masks or there is no SD mask node in this suite. Base mask node doesnt allow to input batch images.

**Comment by WASasquatch** [comment]
I don't think SD even allows batch init. I am not sure what you mean. And Image to Latent Mask allows you to inpaint yes. You have to use the mask latent noise node

**Comment by AbyszOne** [comment]
I was referring to using a batch of masks like the one in the SD gui. Regarding the batches, it is a very useful function but the current implementation has several conflicts. One of the most obvious is that it uses the root folder to host the txt, and that prevents you from using two processes with the same folder, since the batches overwrite each other and add up. It is also not clear how it counts and resets the batches. I have resigned myself to deleting the txt after each round, because it does not restart after finishing the batch. In particular, I am using a workflow that uses the same images in multiple ways, so with the current system I have to create copies and copies of each folder so that the batches do not conflict.

**Comment by WASasquatch** [comment]
You do realize it saved the counter in the image folder you target, and you can name the image counter anything you want like 'counter1.txt` and `counter2.txt` and use same folder. 

And no, no tasks open txt files but my text file loader. Storing the text files is required and the best method because I do thousands of images and need to continue those batches.

**Comment by AbyszOne** [comment]
Well, it makes sense if it's for personal use and you don't expect to be friendly to the general user.
Something that shouldn't be troublesome to change is to create the destination folder if it doesn't exist. It currently reports that it does not exist and stops. It would be very useful when doing multiple tests.

**Comment by WASasquatch** [comment]
Why would it create a destination folder that doesn't exist when it's looking to load files? It will have to error regardless because it can't return anything.

**Comment by AbyszOne** [comment]
> Why would it create a destination folder that doesn't exist when it's looking to load files? It will have to error regardless because it can't return anything.

¿? A destination folder is a destination folder, not an input folder. Why would be a problem creating it? The opposite is the problem, if any.

**Comment by WASasquatch** [comment]
> > Why would it create a destination folder that doesn't exist when it's looking to load files? It will have to error regardless because it can't return anything.
> 
> ¿? A destination folder is a destination folder, not an input folder. Why would be a problem creating it? The opposite is the problem, if any.

I thought we were talking about the load batch images node still.

**Comment by AbyszOne** [comment]
I see. Anw, good suite, more useful than default for sure.

**Comment by WASasquatch** [comment]
> I see. Anw, good suite, more useful than default for sure.

Thank you. I just pushed patch so you can save to destination that doesn't exist: https://github.com/WASasquatch/was-node-suite-comfyui/commit/f73e06061be5c059f2fa5d939f27f454306cc36b#diff-35652c7be27f406523ce77f22809c807782fa83236d30eed7d170b3859941ddbR2054

**Comment by WASasquatch** [comment]
> I see. Anw, good suite, more useful than default for sure.

Load Image Batch is updates and changed a bit. It now stores it's settings internally, but it also allows you to use a pattern glob for the directory. So you could use `**/*` to search the directory and all subdirectories, or `*.jpg` to only select `jpg` images in the directory.

**Comment by AbyszOne** [comment]
Great. Ill send feedback soon.

**Comment by WASasquatch** [comment]
It's checking for the clone folder and file, `was-node-suite-comfyui\WAS_Node_Suite.py`. did you rename the folder or main file?

**Comment by AbyszOne** [comment]
> F:\\AIUI\\ComfyUI/ComfyUI/custom_nodes\\was_suite_settings.jso

No, just normal clone into scripts folders. This is the part im talking about ```F:\\AIUI\\ComfyUI/ComfyUI/custom_nodes\\was_suite_settings.json ```. Thats not a correct path.

**Comment by AbyszOne** [comment]
Full error:
```
 File "F:\AIUI\ComfyUI\execution.py", line 177, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "F:\AIUI\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "F:\AIUI\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "F:\AIUI\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 3 more times]
  File "F:\AIUI\ComfyUI\execution.py", line 65, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 709, in load_batch_images
    fl = self.BatchImageLoader(path, label, pattern)
  File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 728, in __init__
    self.WDB.insert('Batch Counters', label, 0)
  File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 114, in insert
    self._save()
  File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 133, in _save
    with open(self.filepath, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\AIUI\\ComfyUI/ComfyUI/custom_nodes\\was_suite_settings.json
```

**Comment by WASasquatch** [comment]
> Full error:
> 
> ```
>  File "F:\AIUI\ComfyUI\execution.py", line 177, in execute
>     executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
>   File "F:\AIUI\ComfyUI\execution.py", line 56, in recursive_execute
>     executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
>   File "F:\AIUI\ComfyUI\execution.py", line 56, in recursive_execute
>     executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
>   File "F:\AIUI\ComfyUI\execution.py", line 56, in recursive_execute
>     executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
>   [Previous line repeated 3 more times]
>   File "F:\AIUI\ComfyUI\execution.py", line 65, in recursive_execute
>     outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
>   File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 709, in load_batch_images
>     fl = self.BatchImageLoader(path, label, pattern)
>   File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 728, in __init__
>     self.WDB.insert('Batch Counters', label, 0)
>   File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 114, in insert
>     self._save()
>   File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 133, in _save
>     with open(self.filepath, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'F:\\AIUI\\ComfyUI/ComfyUI/custom_nodes\\was_suite_settings.json
> ```

Can you try the latest push? We're not using `os.sep` to try and keep better path separator structure. And now the database is reading and writing in `+` mode which should create the file if it doesn't exist. Apparently normal `w` and `r` creates files on some windows system, but in general, isn't supposed to.

**Comment by WASasquatch** [comment]
> I'd like to understand enough of the code to help, but I can barely get my script to work. What I can tell is that such a was_suite_settings.json does not exist in any folder, and the problem persists with the latest pull. I am not able to render anything.

What OS and venv environment are you running? It creates the file on its own, and does in all my tests on windows 11 and Ubuntu. It's not in `w+` and `r+` mode which create the file if it doesn't exist, so not much I can do beyond that. You can create the file yourself and add `{}` to it.

**Comment by WASasquatch** [comment]
Alright, I added some better file logic. It'll get the file paths based on the executing node file: https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/WAS_Node_Suite.py#L44

**Comment by AbyszOne** [comment]
That solved the wrong path, not the .json issue. I create it and seems to be working. Ill check later.

**Comment by AbyszOne** [comment]
Talked too soon. It creates the output folder, and makes the picture, but didn`t save the picture on: st! Creating directory.
Traceback (most recent call last):
  File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2071, in save_images
    [-1] == "_", map(map_filename, os.listdir(self.output_dir))))[0] + 1
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'F:\\AIUI\\ComfyUI\\ComfyUI\\output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AIUI\ComfyUI\execution.py", line 177, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "F:\AIUI\ComfyUI\execution.py", line 65, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2075, in save_images
    os.mkdir(self.output_dir)
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'F:\\AIUI\\ComfyUI\\ComfyUI\\output'

**Comment by WASasquatch** [comment]
Your system is doing weird stuff to paths lol 

> Talked too soon. It creates the output folder, wich is nice, and makes the picture, but didn`t saved the picture on:
> 
> ```
> st! Creating directory.
> Traceback (most recent call last):
>   File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2071, in save_images
>     [-1] == "_", map(map_filename, os.listdir(self.output_dir))))[0] + 1
> FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'F:\\AIUI\\ComfyUI\\ComfyUI\\output'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "F:\AIUI\ComfyUI\execution.py", line 177, in execute
>     executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
>   File "F:\AIUI\ComfyUI\execution.py", line 65, in recursive_execute
>     outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
>   File "F:\AIUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2075, in save_images
>     os.mkdir(self.output_dir)
> FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'F:\\AIUI\\ComfyUI\\ComfyUI\\output'
> ```
> 
> For instance, my output was nothing remotely close to that path.

That was a little more straight forward of an issue haha. That should be fixed in latest push. Additionally, you an use the prefix as a filename if overwrite is true: https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/WAS_Node_Suite.py#L2037

**Comment by AbyszOne** [comment]
Fingers cross, my system is working on many repos without such behavior yet. Ill test updates asap.

**Comment by WASasquatch** [comment]
> Fingers cross, my system is working on many repos without such behavior yet. Ill test updates asap.

Yeah, this is why people probably use [pathlib](https://docs.python.org/3/library/pathlib.html#module-pathlib) so they don't have to worry about separators and all that stuff, so it just works on any systems file structure.

**Comment by WASasquatch** [comment]
I also went through and made the auto install process be a little smarter about where it's looking and what it's doing. File permissions though is a user-thing. People will have to make sure their ComfyUI  custom-nodes dir and files are writable.
