### ISSUE TITLE
Multiple "load image batch" doesn't change the indexes. 

### ISSUE THREAD

**Issue by Puddz** [WASasquatch/was-node-suite-comfyui#102]
This might be a weird interaction with another extension im using, but I dont see how. Extension in question is: https://github.com/LEv145/images-grid-comfy-plugin

https://files.catbox.moe/8kfbd7.json - mock up workflow cause my explantion is gonna be shit.

Basically I have two folders, "top half" and "bottom half". 
I'm trying to put one image from "top half" and one image from "bottom half" through an img2img on the same workflow then combine at the end. So after the first two are done, the "load image batch" would load the next two images and those next two would go through the img2img process and combine at the end. But this doesn't happen. 
Instead it only loads index image 1 from the "top half" and index image 1 from the "bottom half" for each job on the batch. 

also edit: there's no error to go along with it.

**Comment by WASasquatch** [comment]
If you notice, you're using the same label for both batches, which means the data from both is overriding the others. The labels are used to differentiate the batches.

**Comment by Puddz** [comment]
Ah that makes sense. I'm stupid. Thanks.
