### ISSUE TITLE
Image Blend by Mask: mask input takes image instead

### ISSUE THREAD

**Issue by Bocian-1** [WASasquatch/was-node-suite-comfyui#105]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/70019596/c041361c-80b5-4a9e-9596-0a08278df2f9)

**Comment by WASasquatch** [comment]
Yes, cause it's for raster blending of images, not diffusion masking. Use a `Masks to Image` node if you want to use a mask.

**Comment by Bocian-1** [comment]
Well, it is a bit confusing at first, not gonna lie. Not like I have any good idea of how to help it though.

**Comment by WASasquatch** [comment]
I don't see how. It's a image blending node. Like Photoshop and such. You use raster masks. Mask format is really just in the way and a hassle to deal with on the backend and actually serves no purpose. Handling tensor conversion should be done from one standard format so you can use them whenever. Filter nodes, preview nows, etc.

**Comment by Bocian-1** [comment]
I mean that it being labelled as 'mask' but requiring 'image' is what confused me specifically, that's why I thought it was an error in the first place. Changing the labels around to avoid that seems a bit tricky to do. That is all.

**Comment by WASasquatch** [comment]
Ohh I see. Yeah that could be renamed. I ahd thought of that before but it's not graceful in that it will break everyone's workflows.
