### ISSUE TITLE
Load multiple files to dictionary

### ISSUE THREAD

**Issue by gobshyte** [WASasquatch/was-node-suite-comfyui#113]
Hi
I'm trying to setup a wildcard replacer, if I have 20 (or more) different wildcard files, do I really need to setup 20 nodes to read each file?
Then combine all of those 4 at a time using the dictionary update? 
Or am I missing a node where we can point it at a folder that contains wildcard files?
Thanks

**Comment by WASasquatch** [comment]
Can't you use the CLIPTextEncode nodes under WAS -> Conditioning and use wildcard mode and setup your wildcard dir in config, or move wildcards to /was-node-suitr-confyui/wildcards/ ? The approach you are using is somewhat outdated.

**Comment by gobshyte** [comment]
Ahhhh, I had created and put stuff into that wildcards folder but I thouth that was only for NSP or somehing.
Then I just failed repeatedly, still could not get it to work, until I realised the reference to the file is case-sensitive!
Many thanks, this is perfect
