### ISSUE TITLE
no module named 'Numba'

### ISSUE THREAD

**Issue by mattymatty** [WASasquatch/was-node-suite-comfyui#116]
no module named 'Numba' error

Using portable (Windows)

**Comment by WASasquatch** [comment]
You should take a look at the issues history. Most common issue discussed. 

You need to install everything through your `python_embedded\python.exe` not your system. There is also a install.bat you can find in the was-node-suite-comfyui directory you can try.

**Comment by mattymatty** [comment]
Thank you, I just tried the install.bat but I'm getting this error:

No module named 'pybind11'

**Comment by WASasquatch** [comment]
That's a new one. You can build pyblind11 via these instructions: https://pybind11.readthedocs.io/en/stable/basics.html

**Comment by mattymatty** [comment]
i just installed the non-portable version with conda. It works now, thank you

**Comment by WASasquatch** [comment]
> i just installed the non-portable version of ComfyUI with conda and then this and it works now, thank you

Good to know. Was it full conda or miniconda? Want to look into what conda venv provides.
