### ISSUE TITLE
Would U please make Constant Number  be able to drive LatentImage Size (width and height )?

### ISSUE THREAD

**Issue by BoosterCore** [WASasquatch/was-node-suite-comfyui#12]
Would U please make Constant Number  be able to drive LatentImage Size (width and height )?
With this function, it should be possible to control image scaling more conveniently through the Number Operation node.

**Comment by BoosterCore** [comment]
Sorry, I just found out that Latent Upscale by Factor and Image Resize can solve this problem！

**Comment by WASasquatch** [comment]
Also you should be able to use Number to Int, and Right Click the input and Convert it to Input. Additionally you can use a Primitive in place of a Constant Number and Number to Int (if you aren't using math on them).
