### ISSUE TITLE
Random number can't go into EmptyLatentImage: width

### ISSUE THREAD

**Issue by mattymatty** [WASasquatch/was-node-suite-comfyui#120]

**Comment by WASasquatch** [comment]
Number to Int node

**Comment by mattymatty** [comment]
I appreciate your help but I'm getting this error when i add the final int to the width field.

Prompt outputs failed validation
Number to Int:
- Return type mismatch between linked nodes: number, INT != NUMBER

**Comment by WASasquatch** [comment]
Looks like you already have a int. Hars to know what you are doing without seeing.

**Comment by WASasquatch** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/7e63c3e1-3e08-4f4b-af23-1f9056b353bc)

**Comment by mattymatty** [comment]
The new random node you made works amazing.
