### ISSUE TITLE
[Feature Request]: Change method for wildcards from text files.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [WASasquatch/was-node-suite-comfyui#121]
According to the example below, every text file needs to be declared individually before it can be used. Would it be possible to only declare the wildcard directory and then use the text entries (eg. "__<filename>__") to determine which file to use in that directory? This would then work similarly to how it does in A1111/Vlad.
![Wildcards-with-Dictionary-Text-File](https://github.com/WASasquatch/was-node-suite-comfyui/assets/52193044/0aa8dd64-bb3e-4bd9-9eaf-4b92efa883f7)

**Comment by gobshyte** [comment]
From what I've found, this method/example is old, see here for new method:
https://github.com/WASasquatch/was-node-suite-comfyui/issues/113
