### ISSUE TITLE
Face crop example does not load workflows

### ISSUE THREAD

**Issue by todhm** [WASasquatch/was-node-suite-comfyui#123]
https://camo.githubusercontent.com/227414dc6da877718463683ec2deedd5445b7cfea1a84234592c3d6feae458a2/68747470733a2f2f692e706f7374696d672e63632f33787959547264632f46432d4669782d466163652d43726f702d4e6f64652e706e67
I'm trying to load metadata by downloading following files is there anyway we can download json manually?

**Comment by WASasquatch** [comment]
I am not sure what happened to that workflow. I tend to use the CLIPSeg approach myself. I will try and get new workflows put together as soon as I can.

**Comment by WASasquatch** [comment]
![CLIPSeg_Face_Crop_Cycle](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/408d5983-1f90-41ad-b32d-38f2f5a8ceae)

This is my currently recommended workflow for this in WAS-NS.

**Comment by todhm** [comment]
Great Thanks
