### ISSUE TITLE
Number Operation issue: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

### ISSUE THREAD

**Issue by Bocian-1** [WASasquatch/was-node-suite-comfyui#125]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/70019596/3f8260c2-cea0-4994-a696-e09ab19741b5)

**Comment by poisenbery** [comment]
Getting this error also.
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/78466408/bdfcc26f-53f3-4bef-a914-c13055cef9e5)

**Comment by WASasquatch** [comment]
Hmm seems things are randomly getting contained in extra tuples for some reason.

**Comment by Bocian-1** [comment]
Works now, thank you
