### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by GiChiken** [WASasquatch/was-node-suite-comfyui#127]
Collecting opencv-python-headless[ffmpeg]
  Using cached opencv-python-headless-4.8.0.74.tar.gz (92.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pilgram
  Using cached pilgram-1.2.1-py3-none-any.whl (817 kB)
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg

**Comment by WASasquatch** [comment]
What version of Python are you using ConfyUI on? Can you upgrade pip? ConfyUI Portable is preferred method of use if you are on Windows.

**Comment by GriffinLane** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/31805782/a408cb7a-3407-4a72-8228-06fc8fbab87f)
Can also confirm installs don't work through UI manager nor through manual installation in custom nodes folder. Appears to be a simple error though.
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/31805782/c238a5d2-121c-4687-b51f-69b11865b2ee)

**Comment by WASasquatch** [comment]
I do not support ComfyUI Manager, so it's issues are its own. However you are running commands with your system python from custom_nodes, not through your python embedded... `D:\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip --version`

**Comment by GiChiken** [comment]
python 3.10.6 , pip version 23.2
![캡처](https://github.com/WASasquatch/was-node-suite-comfyui/assets/96877334/d002bbb5-5ebc-4422-9441-40594ff10b1b)

This time I also got this error 
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/96877334/389cd429-950c-4d48-a41b-f2651a3e48f5)
Thank you for your reply, I would like to resolve the issue

**Comment by GiChiken** [comment]
The issue has been resolved.
You can do this by modifying the METADATA of torchsde-0.2.5.dist-info inside the Python Embedded folder
https://github.com/google-research/torchsde/issues/131

I also installed rembg manually and that fixed it, thanks!
