### ISSUE TITLE
tokens variable in create_morph_gif used before creation

### ISSUE THREAD

**Issue by dotJack** [WASasquatch/was-node-suite-comfyui#128]
https://github.com/WASasquatch/was-node-suite-comfyui/blob/963b83db89e675d10369104a76932ee8b5fb663a/WAS_Node_Suite.py#L3595C1-L3595C137

**def create_morph_gif** [L3595]

When setting up the output_path, there's a reference to tokens.parseTokens(.....) on line `3607` but tokens isn't set up until further down on line `3626`.

Maybe it's some python ordering thing I don't understand fully and my setup is actually wrong, but the only way to avoid a message related to this on my setup is to move the initialization for `tokens` towards the top of the method.

**Comment by WASasquatch** [comment]
I think I reorganized the node for some other reason, but it probably did get put out of order.

**Comment by WASasquatch** [comment]
Should be patched.
