### ISSUE TITLE
Is there a Text Node that can drive the filename_prefix in the Image Save node?

### ISSUE THREAD

**Issue by BoosterCore** [WASasquatch/was-node-suite-comfyui#13]
After I converted the filename_prefix to input, I found that no node can be connected to it.
Suppose I want to extract a keyword from the prompt and use it as a prefix of the image document, this function will be helpful.

**Comment by WASasquatch** [comment]
Right Click -> Convert filename_prefix to input
![image](https://user-images.githubusercontent.com/1151589/228773126-866ff338-4f41-4d52-8c38-db6329bea12c.png)
Add Util -> Primitive
![image](https://user-images.githubusercontent.com/1151589/228772953-b9f09c12-021e-446a-ba04-6373593dd093.png)

**Comment by BoosterCore** [comment]
Thank U very much! But Primitive node has no input.
I use Text Multiline, Text Random Line and Text Concatenate to created a dynamic prompt.
I want to make the main subject in the dynamic prompt to name the file prefix automaticly.
My demand may be too strange, sorry！

**Comment by BoosterCore** [comment]
![dp](https://user-images.githubusercontent.com/73834045/228784145-a9f800ee-5e08-4384-9efe-6d323cbdb6bf.png)
I want to read string from here to filename_prefix.

**Comment by WASasquatch** [comment]
Oh I see what you mean!

I'll add some nodes to convert Text to String (I thought about this but must have spaced when doing text nodes. Give me like half an hour to wake up and I'll get that in.

**Comment by WASasquatch** [comment]
There we go, **Text to String** node is added: https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/WAS_Node_Suite.py#L3609

**Comment by BoosterCore** [comment]
Really appreciate your help
