### ISSUE TITLE
Nodes get stuck to cursor when connecting to or from input side of WAS text nodes

### ISSUE THREAD

**Issue by Waiwei8k** [WASasquatch/was-node-suite-comfyui#144]
Running was-node-suite on ComfyUI in an install with only Comfy, node manager and this node pack on Python 3.11.4 on Kubuntu 22.04, I get the following issue:

The standard Comfy nodes work fine, allowing me to freely connect between compatible ports on nodes. I want to add some WAS text processing nodes. After adding the text find and replace node, I try to connect it to the built in default text box. No matter which way I connect (text to find and replace or find and replace to text), the connecting line is drawn, but when I click on the destination node, it gets grabbed by the mouse and I can't put it down after. I have to reload the page or delete the node to fix things. This happens with the connections on the left of the was node. Those on the right work fine.

**Comment by Waiwei8k** [comment]
### Loading: ComfyUI-Manager (V0.15.1)
### ComfyUI Revision: 1218 [c910b4a0]

was-node-suite-comfyui$ git log -1
commit ab454b1c9a5f00fc8b41b91a7ea94d60d901ce50 (HEAD -> main, origin/main, origin/HEAD)
Author: Jordan Thompson <jordanslost@gmail.com>
Date:   Thu Jul 27 10:38:42 2023 -0700

**Comment by MoonRide303** [comment]
Same problem here - I wanted to use WAS for text contatenation, but it doesn't work (latest version of both ComfyUI and WAS), connections cannot be made, and native ComfyUI nodes stick to the cursor, instead (only page reload helps).

**Comment by WASasquatch** [comment]
WAS-NS doesn't really support Python 3.11. It uses older AI tools based around colabs for 3.8,3.9, the fact they work on 3.10 is great but 3.11 is pushing it. However this is just a node pack. It in no way affects the front end so that sounds like a bug with it handling custom data types.

**Comment by MoonRide303** [comment]
@WASasquatch In my case it happens with Python 3.10.11 (Anaconda for Windows).

**Comment by Waiwei8k** [comment]
Thanks for the feedback. I'm away for a few days. I'll look at getting the report in on Comfy when I get back.

**Comment by WASasquatch** [comment]
> @WASasquatch In my case it happens with Python 3.10.11 (Anaconda for Windows).

I wasn't referring the the error in general but that you may run into more issues.

**Comment by WASasquatch** [comment]
I believe this issue has been resolved in base ComfyUI.
