### ISSUE TITLE
Image Save node error after update

### ISSUE THREAD

**Issue by manny5457** [WASasquatch/was-node-suite-comfyui#145]
Hi. The image save node worked perfectly and after updating WAS nodes this morning it now gives me the following error "   - Required input is missing: filename_number_start", there is no input for file number and before the update, it would just save into the folder and continue from the last file number. any help to resolve this would be appreciated. thanks

**Comment by manny5457** [comment]
think I resolved it be reloading the node. thanks

**Comment by WASasquatch** [comment]
Yeah I was updated with a new feature via PR. ComfyUI is totally not graceful about node field order changes
