### ISSUE TITLE
Image Save: Embed workflow does not work for jpeg or webp

### ISSUE THREAD

**Issue by mattymatty** [WASasquatch/was-node-suite-comfyui#148]
Image Save Node: Embed workflow does not work for jpeg or webp

it DOES work for png.

**Comment by WASasquatch** [comment]
ComfyUI only reads PNG workflows, and I do not deploy any custom modifications to the front end. They are all done in hacky unofficial ways.

**Comment by mattymatty** [comment]
That's not correct. ConfyUI 100% reads webp metadata

**Comment by WASasquatch** [comment]
> That's not correct. ConfyUI 100% reads webp metadata

If so, that is relatively new, as it's a common discussion in Element. Are you sure you don't have Mike's extension that adds webp drag drag support? Even the readme still only lists PNG.

**Comment by mattymatty** [comment]
You are correct. This https://github.com/Kaharos94/ComfyUI-Saveaswebp both saves metadata to webp and also loads it.
