### ISSUE TITLE
Would U please make a node to convert random number into string?

### ISSUE THREAD

**Issue by BoosterCore** [WASasquatch/was-node-suite-comfyui#15]
I use "Random Number" node to drive the seed in KSampler(WAS), so I really need a node to convert the random number into string, so that it will be added to the suffix of the image file.

**Comment by WASasquatch** [comment]
Good idea. I'll get that in today.

**Comment by WASasquatch** [comment]
Alright, that should be in the latest push.

**Comment by BoosterCore** [comment]
"[time]" works perfect in "Save Text File" now,
Would U please make it work in "Image Save" too?

**Comment by WASasquatch** [comment]
Old (updated BoosterCore's message accidently or posts merged somehow): Hmm. Probably should rewrite it to be a tag parser class or something so I can handle the tags from multiple nodes without doing the same code over and over. I'll take a look at that in a bit. 

Update: Token system is in place now.
