### ISSUE TITLE
Missing node of WAS Node Suite after installing

### ISSUE THREAD

**Issue by wardensc2** [WASasquatch/was-node-suite-comfyui#154]
Hi, I just install your node suite by using ComfyUI Manager but Comfy just show missing the 2 nodes: 
- Text Multiline
- Image Save

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/77379748/d417edb0-b69f-4f29-bebb-76735241adbe)

How do I fix this problem

Thank you in advance

**Comment by WASasquatch** [comment]
There is likely an error in your console which would tell us what is wrong. But the likely culprit is not installing correctly.

**Comment by auroraTDunn** [comment]
I have the same issue. I've tried installing via the ComfyUi Manager, from Civitai, and the manual way with git clone and pip installing requirements.txt as per the instructions.
I get no errors with any of these methods when installing and get no messages in the console, nor in comfyui.log.
When I 'think' its installed I go into Comfy and see no WAS node suit under Custom Nodes (it exists in the custom_nodes directory but Comfy does not see them when you try to add a node). If I load a json, or png which utilizes any WAS nodes I get an error similar to the OP image stating that it can not find them. If I open the Manager to install missing nodes it finds the WAS suite is installed giving me the option to disable or uninstall.

**Comment by WASasquatch** [comment]
Sounds like you are all installing to your systems python and not ComfyUI
Standalone Portable installations python.exe found in python_embeded. You
will need to uninstall from the system and install properly with the
portables exe like it shows In the directions with the full path to the
exe.

There is also a install.bat which should automatically detect portable
install if you have the install in was-node-suite-comfyui in custom_nodes

**Comment by auroraTDunn** [comment]
That was exactly it. I thought I had it linking to the Comfy python version not one of my others (I have several since I teach Python a lot).
Its working now THANKS!
