### ISSUE TITLE
installing problem (access denied)

### ISSUE THREAD

**Issue by xxl2005** [WASasquatch/was-node-suite-comfyui#155]
hello

i have a problem i can
what node suite not install
What do I have to do to be able to install?

OS linuxmint 21

`obias@tobias-B550I-AORUS-PRO-AX:~/ComfyUI-master$` python3 main.py

Prestartup times for custom nodes:
   0.0 seconds: /home/tobias/ComfyUI-master/custom_nodes/ComfyUI-Manager

Total VRAM 16080 MB, total RAM 64184 MB
xformers version: 0.0.20
2023-08-05 17:43:36.042888: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-05 17:43:36.652031: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA Graphics Device : cudaMallocAsync
Using xformers cross attention
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
Total VRAM 16080 MB, total RAM 64184 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA Graphics Device : cudaMallocAsync
WAS Node Suite: Created default conf file at `/home/tobias/ComfyUI-master/custom_nodes/was-node-suite-comfyui/was_suite_config.json`.
WAS Node Suite: Installing `opencv-python-headless` ...
Collecting opencv-python-headless[ffmpeg]
  Using cached opencv_python_headless-4.8.0.74-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.1 MB)
WARNING: opencv-python-headless 4.8.0.74 does not provide the extra 'ffmpeg'
Requirement already satisfied: numpy>=1.19.3 in /usr/lib/python3/dist-packages (from opencv-python-headless[ffmpeg]) (1.21.5)
Installing collected packages: opencv-python-headless
ERROR: Could not install packages due to an OSError: [Errno 13] access denied: '/usr/local/lib/python3.10/dist-packages/opencv_python_headless.libs'
Consider using the `--user` option or check the permissions.

Traceback (most recent call last):
  File "/home/tobias/ComfyUI-master/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tobias/ComfyUI-master/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/home/tobias/ComfyUI-master/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 13067, in <module>
    subprocess.check_call([sys.executable, '-s', '-m', 'pip', 'install', 'opencv-python-headless[ffmpeg]'])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-s', '-m', 'pip', 'install', 'opencv-python-headless[ffmpeg]']' returned non-zero exit status 1.

Cannot import /home/tobias/ComfyUI-master/custom_nodes/was-node-suite-comfyui module for custom nodes: Command '['/usr/bin/python3', '-s', '-m', 'pip', 'install', 'opencv-python-headless[ffmpeg]']' returned non-zero exit status 1.

Import times for custom nodes:
   0.0 seconds: /home/tobias/ComfyUI-master/custom_nodes/SeargeSDXL
   0.0 seconds: /home/tobias/ComfyUI-master/custom_nodes/ComfyUI-Manager
   8.9 seconds (IMPORT FAILED): /home/tobias/ComfyUI-master/custom_nodes/was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188`

**Comment by WASasquatch** [comment]
Are you using linux? You'll need to run the requirement installation with elevated privileges, or like it says, try `--user`
