### ISSUE TITLE
Image Blend by Mask node should have blending mode input

### ISSUE THREAD

**Issue by srbustdown** [WASasquatch/was-node-suite-comfyui#159]
Image Blend by Mask: 
I would like to blend two images by a mask with the option of selecting the blending mode as an input i.e. add/multiple/screen/overlay

The inputs should be as follows:
Image A
Image B
Mask
Blend Percentage
Blend Mode

There might be a better way to do this but I'm not that familiar with alternative methods of image editing using a node based approach.

TLDR: 
Added a screenshot at the bottom to help visualize the workflow. Ignore the placeholder image and bad mask.
Separate foreground and background. 
Apply a "brightening effect" to foreground and a "darkening effect" to the background to make the "subject" of an image pop more.

The workflow I'm going for is:
1. Separate the foreground and background using a mask (ControlNet Depth)
2. Take the Foreground mask that ControlNet Depth provides and invert it to get the background mask.
3. Connect original image that was fed into ControlNetDepth as input A in the Image Blend by Mask node.
4. Connect a "brightening image" as input B to Image Blend by Mask node.
5. Connect the mask given from ControlNet Depth to the mask input Image Blend by Mask node.
6. Set the percentage based on how much I want to affect the foreground.
7. Set the blend type based on whatever I want to do to the image like photoshop layers (overlay/multiply/etc) => Blended Image A
8. Invert the "brightening image" to make a "darkening image" as input B to another Image Blend by Mask node.
9. Invert the mask given from ControlNet Depth to the mask input Image Blend by Mask node.
10. Connect original image that was fed into ControlNetDepth as input A in the Image Blend by Mask node.
11. Set the percentage based on how much I want to affect the foreground.
12. Set the blend type based on whatever I want to do to the image like photoshop layers (overlay/multiply/etc) => Blended Image B
13. Take blended image A and Blended Image B and blend them together with a Image Blend node.

![Screenshot 2023-08-12 191253](https://github.com/WASasquatch/was-node-suite-comfyui/assets/109939968/3704cccf-93ab-4f38-a568-cb3016ae6dd6)
![Screenshot 2023-08-12 184949](https://github.com/WASasquatch/was-node-suite-comfyui/assets/109939968/72521a10-b165-48d2-9ca3-44bbe32fa0ae)

**Comment by WASasquatch** [comment]
Just Image Blend with a mode, and Image Blend that.

**Comment by srbustdown** [comment]
Sorry I don't understand, can you share a screenshot?

**Comment by WASasquatch** [comment]
If all you are doing is wanting to blend mode or w/e you just blend however, and then blend that. 

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/2469cc42-eccf-447c-9bb2-347ec2a49ab3)
Workflow:
![ComfyUI_00916_](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/0a7d52cf-457e-4723-bcc9-c98a67ac37b6)


If you want a blending node like that, you're welcome to PR it, but it's not much a concern for me.

**Comment by srbustdown** [comment]
Thank you, that is exactly the effect I wanted. Sorry I did not know you could combine the image blend by mode and image blend by mask nodes in that way.

**Comment by WASasquatch** [comment]
I added that idea to my to-do list, I'll add it eventually lol. Would be more simple for straight forward merges that don't need extra post.
