### ISSUE TITLE
all text node do not work

### ISSUE THREAD

**Issue by pzzmyc** [WASasquatch/was-node-suite-comfyui#173]
My English is not very good, I can not write, thank you very much for using just 1 minute to watch video

https://github.com/WASasquatch/was-node-suite-comfyui/assets/43562427/605e4e3d-6434-44e5-a3cc-4b3726d8f886

**Comment by WASasquatch** [comment]
That's related to this bug and forceInput nodes. They're not all broken, just the node you're trying to hook up too with another custom node. Try using a primitive for the multiline text. 

There is a fix for it in this PR: https://github.com/comfyanonymous/ComfyUI/pull/1104

**Comment by pzzmyc** [comment]
thanks，Thanks. It's my problem.，multiline is working
