### ISSUE TITLE
After the latest upgrade, there was an error when using the Voronoi Noise node. 

### ISSUE THREAD

**Issue by sober54** [WASasquatch/was-node-suite-comfyui#175]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/add6f977-186a-4de9-bfb4-6adfa97b773d)
Error occurred when executing Image Voronoi Noise Filter:

setting an array element with a sequence.

File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 4221, in voronoi_noise_filter
image = WTools.worley_noise(height=width, width=height, density=density, option=modulator, use_broadcast_ops=True, flat=(flat == "True")).image
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2082, in __init__
self.image = self.generateImage(option, flat_mode=flat)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2116, in generateImage
non_flat_black_adjusted[h, w] = self.data[h, w] + self.data[closest_point_idx]

**Comment by WASasquatch** [comment]
Oops. I didn't mean to push that :P

https://github.com/WASasquatch/was-node-suite-comfyui/commit/0df641643de84ceb21ac55e4de3a65f07ee64ab6

**Comment by sober54** [comment]
Thank you for your work  ":P"  . your node now functioning, but I have encountered a new issue in my workflow. Let me provide some context. My workflow combines two types of noise spaces: a colorful grain noise image and your Voronoi Noise image. This combination generates a new noise image. I have tried all the noise nodes, and your Voronoi Noise node adds more details to the generated image. However, I am unsure whether it is the shape or color that is influencing the result
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/9a8a5d8a-3b5d-4afc-8179-1aca6625e007)
This method allows the generated image to be controllable on many levels. There are many parameters that can be adjusted, and they will be reflected in the final result, such as color, sharpness, and details. However, the issue I encountered after this update is that the two types of noise cannot blend together
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/6a90bb7f-ada3-48ac-b097-1bf727ffea7a)
Error occurred when executing VAEEncode:

too many indices for tensor of dimension 3

File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 276, in encode
t = vae.encode(pixels[:,:,:,:3])
Forgive my limited GPTEnglish , not fully express my gratitude and respect. Love from China, and I appreciate your efforts.

**Comment by sober54** [comment]
![动漫-2 5-《唯》系列炫彩动漫 _ OnlyAnime_v2 追光 safetensors_00135](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/441397af-f0ee-49b5-b7d6-83f9daecca4e)
![真实-TWing Film wind 光影摄影_v1 3 safetensors_00100](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/f1aec462-ef6e-4518-af38-67b82885d4e5)
![真实-TWing Film wind 光影摄影_v1 3 safetensors_00101](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/ed148c12-1eec-438b-b0c9-8de26ccca1ad)
This is something I generated, and I feel it is good in terms of details and colors

**Comment by WASasquatch** [comment]
Ah, that is because the noise is natural color (RGB) while the voronoi is linear grayscale. I suppose we would need a Linear to RGB node similar to RGBA to RGB

**Comment by WASasquatch** [comment]
Alright, you'll need to fix the order of inputs on the nodes, but I've added optionals, including "RGB_output" which will convert the images to RGB or Linear on output. There is also Images to RGB and Images to Linear nodes now under WAS Suite/Image menu.

**Comment by sober54** [comment]
new noise looks very juicy, can't wait to try it. Thanks again for your great work. The reason I use this workflow is to generate decent images with 20 iterations on my low-performance graphics card. So, your node practically saved my life. I can even calculate the exact time of the life you saved,love from china again,thanks again

**Comment by WASasquatch** [comment]
Would a number of images from the noise nodes help? Like if you select 4 you'd get four noise images with each images seed incremented?

**Comment by sober54** [comment]
I will test and provide feedback as soon as possible because the two noise nodes I am using can already provide rich variations by changing parameters. Additionally, changing the parameters of the bland node can also bring about changes. So, I mostly use fixed seeds

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/c967ebb1-bffd-411a-bc46-3e53153ff023)
I actually use your latent bland node, which provides functionality similar to Photoshop's layer blending modes

**Comment by sober54** [comment]
latent blend node still got "too many indices for tensor of dimension 3"error
color mode
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/596cd22a-22ad-454e-b702-8d3fe86738aa)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/9f640a32-08f0-4fe0-90d6-1af246673445)

black n white
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/4a91fb67-90f7-46f5-a7c4-be7eb8cb3cf9)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/a7ba85ec-f8fe-4350-b8b6-6eb61201f607)
max modulator
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/27e623a7-5ad1-446f-ad04-12e2fdcc8fc3)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/b89afafd-1764-4031-8fd7-c5af22739701)
min
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/c258c152-0c84-4b2d-8452-3c6844ce4ae6)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/318884f1-57dd-4ead-8286-8e3a8127a823)
 it just working ,your magic is restored, and I'm so happy, I will adjust the input order and try the method of latent blending again. Thank you for your great work

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/1cad1ba7-6056-4301-83ca-cf46eebb858e)
Error occurred when executing VAEEncode:

too many indices for tensor of dimension 3

File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\sober\compyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 276, in encode
t = vae.encode(pixels[:,:,:,:3])
latents blend node still got this,when i use 2 of your Voronoi Noise node,but works fine whan i use that old color plasma node,I believe that after synthesizing multiple noisy images, the resulting latent space should also have these small color blocks. These latent space images have enough white, black, and other colors to make the lighting and shadows in the image look more natural. The small details are also more prominent due to the presence of shadows. These are just my speculations, and I don't know if the algorithm delves into this level. But based on my observations, there is indeed such an effect. With your help, the pasta monster is now flying
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/355a0c18-6bed-4f7e-8f50-efda481c0dfe)

**Comment by WASasquatch** [comment]
I couldn't get the "too many indices for tensor of dimension 3" error using the blend node myself. Here is the workflow I tried:

[NoiseWorkflow.zip](https://github.com/WASasquatch/was-node-suite-comfyui/files/12416682/NoiseWorkflow.zip)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/e4edb439-6a47-4264-beb4-6eac48661409)

**Comment by WASasquatch** [comment]
No problem. Btw in the workflow, I found that blending in your starting noise before doing the final steps like I did in that workflow above, somehow adds extra details when it starts diffusing the second KSampler (Advanced). I don't know how or why, but it does.

**Comment by sober54** [comment]
I don't know either, I can't test the xl model, but it also happened in the 1.5 model. I use TTN suit, and its advanced sampler has an option to add noise, so the same thing should have happened here.
https://github.com/tinyterra/ComfyUI_tinyterraNodes

**Comment by sober54** [comment]
If you manually input the last digit of the blend value, 0.00X (X being a specific value), you can still adjust these details in the case of a fixed seed

**Comment by WASasquatch** [comment]
I have been playing around with building starting noise too with power fractal shader. I create RGB noise with 3 randomly seeded nodes and encode to latent, then run them with two KSampler advanced for 1 step separately and Blend Latents those results, then use that as the latent for generations. 

![ComfyUI_01599__20230823201447](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/19c4bbb0-2a2d-45b9-bcc0-1e1507dc10c5)

**Comment by sober54** [comment]
holy ......good one
I think I know what's going on. It's indeed the black and white that are at play. The AI has learned how to draw black, but we're only giving it a brown or colored latent input
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/e2f7345d-1e02-4d7c-a5e4-1f39b6594051)

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/b0fa1c1b-4b14-4beb-a5ea-6d7c550948d6)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/8750b11e-4555-47b0-9b2e-52d90f87f4ed)
I have added another node after your node to generate noise for the image, but that node has RGBA channels, and it seems that transparency is also affecting it.

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/e9892b7c-eaaa-40c0-a90e-c8f0c5c10b9e)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/5e6c069f-7743-4cf6-bb85-ea2245ef24ce)
By using your node and changing the madulator value to 8, all the black colors are gathered in the center of the image. Then, applying the subsequent node to the transparency channel, I have been able to create many things that resemble non-human creations today. However, since I'm not using the usual workflow, I didn't save them. You can also give it a try. I also discovered that the 2.1 model is very useful today

**Comment by sober54** [comment]
https://drive.google.com/file/d/1871LDE2t7w8Wtfw8RRdPrFbZOHhYvVbR/view?usp=drive_link
This is that workflow, I can only use it for drawing, but I feel like you can create something great with it

**Comment by WASasquatch** [comment]
That's interesting on the last one, wow. Going to have to check it out.

**Comment by sober54** [comment]
I'm glad you decided to give it a try. With a sufficiently high CFG value, along with the effect of node #18, that kind of picture will appear. #15 only provides color, and I'm unsure if the a and b values of node #18 control the position or width. The width of the image I drew is 768, and I set the a value to half of the width. The content in the middle of the picture starts to become very rich. I'm sharing this workflow with you.
![workflooow](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/11eb5e87-0a33-4285-ac67-2f7ac710fe9d)


![ComfyUI_00347](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/e994e62f-fcbe-4da1-b3e0-cd14b2dde4c4)

![ComfyUI_00346](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/49daafb8-8539-4ab4-979f-e03030c0acc3)

**Comment by WASasquatch** [comment]
That's a really amazing. I could see those being the visual effects applied to some sort of character in a epic movie. Main villain or something

**Comment by sober54** [comment]
My workflow is more like stacking garbage, yours is more functional and enjoyable. I will try to add more controllable steps to your workflow, such as incorporating the node for content expansion. Then I will test if it is compatible with Lora, even for those detailed Lora aspects. Even with the 1.5 model, I have achieved some good results
![ComfyUI_00039_](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/a3a10fcb-437f-4fd7-b433-50e38e5f1fb6)

**Comment by sober54** [comment]
Can I attach this issue link and workflow link to the post I am  post on civtai? I think your workflow works better and only requires your node package, making it simpler，looooove form china

**Comment by WASasquatch** [comment]
Yeah that's fine, though should this be kept open?

**Comment by sober54** [comment]
I think it would be great if you could publish a new workflow on c, as you would be able to explain how it works more clearly. This should help close this issue

**Comment by WASasquatch** [comment]
> I think it would be great if you could publish a new workflow on c, as you would be able to explain how it works more clearly. This should help close this issue

Kinda thinking of making a node based on the process that outputs a latent.

**Comment by sober54** [comment]
lmao，please make it happen

**Comment by WASasquatch** [comment]
> lmao，please make it happen

https://github.com/WASasquatch/was-node-suite-comfyui/commit/4d41e150efa540a2eb5db192e50a4698812b3a31

**Comment by sober54** [comment]
Thank you, sir. I apologize for taking so long to provide feedback. I spent a long time testing, and the higher the octaves and exponent, the more details are available. However, a high lacunarity value is needed to showcase these details. Before '34, 'Result too large,' this should be the setting with the most details. With this setting, accessories even interact with the skin on the face.
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/814369d6-b850-41a0-b774-189fad48a5c3)
![mxscale-mxpersis-10lac-exp_00077](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/6a92f07b-86e4-4a4e-a937-614c7079706b)
![mxscale-mxpersis-10lac-exp_00078](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/591ae63f-6a94-4751-966b-204bc418cb47)
![mxscale-mxpersis-10lac-exp_00079](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/24074058-2c88-4f4e-96c9-3e2510c8be6b)
I saw this mug culture outside of China in movies. I wonder if you also like it,But in my country, people who provide high-quality code and share it are referred to as 'Cyber Buddha'  '赛博菩萨'.
![mxscale-mxpersis-10lac-exp_00092](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/0c22ade8-741b-4a1b-8627-5c1b9ca595be)
![mxscale-mxpersis-10lac-exp_00094](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/37461887-ff55-415e-a30d-6efbefeff172)
![mxscale-mxpersis-10lac-exp_00129](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/c4b77ca5-039c-4fdb-82d4-cfb337c4ed00)
![mxscale-mxpersis-10lac-exp_00150](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/03f06b2e-0eca-4053-a082-31bc101651c5)

**Comment by sober54** [comment]
Alpha Channel can also be used as latent. I created such an image yesterday without using any lora
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00145](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/87d6bc19-d26b-440c-bfb5-848edf9ba138)
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00141](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/5bff0f3f-2593-4016-9ea8-027d9f9aad7a)
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00119](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/c604cbde-a31a-499a-8dfa-363a49d69daf)

**Comment by WASasquatch** [comment]
These area all really cool, and they all seem to have a very unique cirsp look to them that I haven't really seen before. That's cool. I like the "Cyber Buddha" saying. It's wholesome. Great work here. Really showed how this node can shine.

**Comment by sober54** [comment]
You are the comfy cyber Buddha. If someone did this during the 1.5 era, I think MJ would have no chance. My computer configuration is too low, it takes more than 120 seconds to generate a 1024² image. There are too few samples to draw any conclusions. So, we still need someone from civtai to test which type of noise is actually at work and find more specific control methods. If you agree, I will attach the address of this issue. Thank you for your efforts and thank you for all great nodes
1.5
![mxscale-mxpersis-10lac-exp_00208](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/1c12ca26-ad44-47ba-95f2-303c214940e1)
2.1
![mxscale-mxpersis-10lac-exp_00209](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/34266a1d-1525-4d9a-9b00-3aaf37a24ce7)
xl
![mxscale-mxpersis-10lac-exp_00211](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/2bb04931-5268-4bf2-b522-55f1a55455ff)
mj
https://lexica.art/?prompt=833f8d1b-c313-4e34-8256-28a4cca64f73

**Comment by WASasquatch** [comment]
Wow. That's really impressive actually. And thank you for the kind words friend.

**Comment by WASasquatch** [comment]
> You are the comfy cyber Buddha. If someone did this during the 1.5 era, I think MJ would have no chance. My computer configuration is too low, it takes more than 120 seconds to generate a 1024² image. There are too few samples to draw any conclusions. So, we still need someone from civtai to test which type of noise is actually at work and find more specific control methods. If you agree, I will attach the address of this issue. Thank you for your efforts and thank you for all great nodes 1.5 ![mxscale-mxpersis-10lac-exp_00208](https://user-images.githubusercontent.com/3257317/263508808-1c12ca26-ad44-47ba-95f2-303c214940e1.png) 2.1 ![mxscale-mxpersis-10lac-exp_00209](https://user-images.githubusercontent.com/3257317/263508817-34266a1d-1525-4d9a-9b00-3aaf37a24ce7.png) xl ![mxscale-mxpersis-10lac-exp_00211](https://user-images.githubusercontent.com/3257317/263508824-2bb04931-5268-4bf2-b522-55f1a55455ff.png) mj https://lexica.art/?prompt=833f8d1b-c313-4e34-8256-28a4cca64f73

Maybe you can help me add some comparison images to this repos paper; https://github.com/WASasquatch/PPF_Noise_ComfyUI/blob/main/perlin_power_fractals_and_latent_diffusion.md

**Comment by sober54** [comment]
Thank God I can finally provide some help for you. Shall I upload some images that I think are good to Google Cloud? Is that enough?

**Comment by sober54** [comment]
I found all my prompts on Civitai and Lexica, just to test if I could recreate the images on Civitai.

**Comment by sober54** [comment]
Or I can now conduct some specific tests, such as examining the variations in texture, color, details, and other aspects using the same prompts

**Comment by WASasquatch** [comment]
If you can do some grid comparisons that would be great. Maybe comparing against base ComfyUI noise in regular KSampler simple. I will try to do some tomorrow if I have time. It's late here now. Spent all evening trying to right a paper describing the process and potential haha

**Comment by sober54** [comment]
Test environment description: I will be working with the 2.1 model (rmada merge) and lock seed number 1 to generate 768*768-sized images. I will be using the advanced K-sampler built into comfyui, with both K-samplers set to the same values. No negative prompts will be used for the samplers. I believe I have created a fair platform to compare the two lanterns. Additionally, to account for the impact of computer hardware temperature on image quality, each test will have a five-minute interval. I have also provided the download for the workflow used in this test. The test content will be limited based on prompts. All prompts will be limited to comparing the following aspects against a black background: rainbow (color comparison), plastic bag (transparency, i.e., how white is handled, and details such as folds, i.e., black contrast), metal ball (comparison based on texture, although it's difficult to quantify, I just like metal balls), and glass cup.

**Comment by sober54** [comment]
I will test it this way, and I will also add some fluffy things into it,I should also add some scenes into it, such as a cozy bed. My previous workflow did generate that cozy feeling
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00055](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/9d9ae84e-b998-47db-9cce-78baf17d5a05)

**Comment by sober54** [comment]
It should be done, sir. I have uploaded the images to the readme.md. You may need to organize them yourself to avoid me messing up what you have written

**Comment by WASasquatch** [comment]
Thank you! I'll take a look as soon as I am at the computer.

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/33482b20-fa65-4b2b-9f2c-7399008a1d93)
I need more colored pencils vs I need to draw that face well

**Comment by WASasquatch** [comment]
> ![image](https://user-images.githubusercontent.com/3257317/263561504-33482b20-fa65-4b2b-9f2c-7399008a1d93.png) I need more colored pencils vs I need to draw that face well

Haha nice. :3

By the way, I just pushed contrast and brightness to repo. Try 0.45 brightness and -0.75 contrast vs default 0.0. You'll notice it seems to add a lot of details.

**Comment by sober54** [comment]
Okay, sir. I will start extensive testing. Thank you for your contribution. Thank you, thank you, thank you, thank you

**Comment by sober54** [comment]
The perfect smoke and accurate lighting that I have been anticipating have finally appeared
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/f6050b2d-3bba-4d40-9ea6-a931c81ab8da)

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/2927ff0d-db03-45f1-836f-d9b0634573f8)
this......
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00290](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/fd5abf58-3cf3-4633-817e-6e17fcb29fac)

**Comment by sober54** [comment]
It is now in the bag

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/e0f827d5-4acd-461f-a4ac-aafd9a0244a1)
Incredibly good
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00293](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/109f2d5d-44a7-4c4f-ab74-1d7d275a0844)

**Comment by sober54** [comment]
赛博菩萨

**Comment by sober54** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/5db07f60-0fc4-404e-a609-634af7d1d238)
![2 1-rMada Merge - SD 2 1 768_v7 0 safetensors_00295](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3257317/16b800f9-57af-4d28-b48a-13cb2f49fdee)

**Comment by WASasquatch** [comment]
It's definitely subjective in some gens, I've noticed from my experimenting, but overall it does seam to lean towards better gens, and even prompt interpretation. Like when I do a product or character concept, I often get ***just*** the subject on plain background, where regular noise will put in random backgrounds. 

I'm going to close this topic, but we can continue to discuss. Since the original problem is solved.

**Comment by sober54** [comment]
Certainly, sir. This issue is like for solving an input error, you are improving this world .

**Comment by WASasquatch** [comment]
> I think you need to enter a complete and user-friendly node description in the readme. Move those comparison images to another place so that I have a space to put more images

Could probably activate and use the wiki thing.

**Comment by sober54** [comment]
Okay,let me know if you need anything

**Comment by WASasquatch** [comment]
Added a wiki: https://github.com/WASasquatch/PPF_Noise_ComfyUI/wiki

And I redid the readme, moving old stuff to `old_readme.md` so it looks more tidy.

**Comment by sober54** [comment]
it's done sir

**Comment by WASasquatch** [comment]
Nice, though maybe name it something like "Walkthrough". Also to note, you do not need to input a VAE. That is optional.

**Comment by sober54** [comment]
CUDA latent is absolutely genius, as it seems to solve the problem with VAE
