### ISSUE TITLE
Seed Deprecation

### ISSUE THREAD

**Issue by gobshyte** [WASasquatch/was-node-suite-comfyui#196]
Hi
Please don't deprecate the Seed node just yet? As far as I can see the primitive seed is a pain to use, because you cannot use it with reroute nodes? Just tried updating everything and lots of primitive nodes (including seed)) are still not working with reroutes :(

**Comment by gobshyte** [comment]
https://github.com/comfyanonymous/ComfyUI/pull/785
Hopefully will be fixed soon though...

**Comment by WASasquatch** [comment]
Alight. Instead I have upgraded it.

https://github.com/WASasquatch/was-node-suite-comfyui/commit/c2b514aae4f9bc74d6f2711a61ab4b85d32dd696
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/69242ce6-99ca-4156-9366-8bcf9891e666)
