### ISSUE TITLE
"Size must be a tuple" error in "Image Rotate Hue"

### ISSUE THREAD

**Issue by Pos13** [WASasquatch/was-node-suite-comfyui#208]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/64479446/ede25204-1e5d-451d-87c5-822731736022)

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/was-node-suite-comfyui/commit/17d45af8be27c724be3d75c9c1e3556a7d2cfc98

Should be patched.
