### ISSUE TITLE
Are "[time]" and seed from the same data source?

### ISSUE THREAD

**Issue by BoosterCore** [WASasquatch/was-node-suite-comfyui#21]
I tried to use "Random Number" to drive the seed of "KSampler(WAS)", and I add it to Image naming use "Number to Text", I used "Save Text File" with "[time]" to  save prompt.
But ... every queue, Random Number give me "0". 
![微信图片_20230402153721](https://user-images.githubusercontent.com/73834045/229339391-707f7989-88fa-4568-b14d-1dfbc8eef325.png)
![微信图片_20230402153725](https://user-images.githubusercontent.com/73834045/229339399-3d73ca79-edfd-4472-8c23-871b6f76fded.png)
![微信图片_20230402153730](https://user-images.githubusercontent.com/73834045/229339402-49c29b60-1030-4415-a889-3913c3f1b66e.png)
![微信图片_20230402153735](https://user-images.githubusercontent.com/73834045/229339406-63fba755-8861-4eb6-9da5-836174ebbd54.png)
![微信图片_20230402153739](https://user-images.githubusercontent.com/73834045/229339409-9337ecc5-c882-4095-9cd4-65273c67e32c.png)

**Comment by BoosterCore** [comment]
"Random Number"  will only give me a float number from minimum to maximum?If so, then a node that converts the seed to text may be needed.

**Comment by BoosterCore** [comment]
I set the maximum,it give other numbers between mini and max now. It seems to prove my idea, random number and seed are not directly equivalent.

**Comment by BoosterCore** [comment]
So looking forward to the solution you mentioned at the end of the discussion below, hopefully "[time]" will work in Image Save. By the way, are "[time]" and Seed really equivalent?
#15

**Comment by WASasquatch** [comment]
Time is microtime, that can be converted into dates and such. Same thing images are saved with in WebUI if you don't save with prompt. Seed is a random int with a extremely high ceiling (too high honestly, can cause errors in programs).

**Comment by WASasquatch** [comment]
So the tokens can now be used in Save Text File and Save Image node, additionally, you can add your own tokens as well.

https://github.com/WASasquatch/was-node-suite-comfyui#text-tokens

![image](https://user-images.githubusercontent.com/1151589/229379144-5bdf78de-dabc-4062-9aef-0628c4aea2da.png)
![image](https://user-images.githubusercontent.com/1151589/229379149-8ac4eb1a-1eea-483a-833b-aae5f333362f.png)

**Comment by BoosterCore** [comment]
Thank you very much for your detailed answer and these great improvements！

**Comment by BoosterCore** [comment]
> > Thank you very much for your detailed answer and these great improvements！
> 
> Thank you! Just added ability to import a1111 styles file just now. Bed time for me.

I have tried it, I have modifyed the styles.csv location in json, but it seems not working, Prompt Styles Selector keep display "None" 
Here is my styles.csv, Is it possible that it's still an issue with UTF-8?
[styles.csv](https://github.com/WASasquatch/was-node-suite-comfyui/files/11150110/styles.csv)

**Comment by BoosterCore** [comment]
> > Thank you very much for your detailed answer and these great improvements！
> 
> Thank you! Just added ability to import a1111 styles file just now. Bed time for me.

I have tried it, I have modifyed the styles.csv location in json, but I got errors and red nodes.
![微信图片_20230404232036](https://user-images.githubusercontent.com/73834045/229839977-7cf4d925-c0bd-4894-a27f-df216419b680.png)
![微信图片_20230404232040](https://user-images.githubusercontent.com/73834045/229840017-90690f7c-1b2e-4c50-a172-b75237356938.png)

**Comment by BoosterCore** [comment]
Here is my styles.csv
[styles.csv](https://github.com/WASasquatch/was-node-suite-comfyui/files/11150234/styles.csv)

**Comment by WASasquatch** [comment]
Oh your file isn't messed up like mine is. Both mine from older WebUI, and new version has weird encoding like it's utf-16 (but it isn't) so I had to add some catches for the weird characters. But looks like your file is clean, with none of that issue.
