### ISSUE TITLE
[feature request] image name input and output

### ISSUE THREAD

**Issue by Kiaazad** [WASasquatch/was-node-suite-comfyui#222]
Save image node is a pretty handy tool, it is a bit tricky to sync two of it to save files with the same name though.
It would be great if you add image name output and inputs so I can have one make the image name and the other copy it.

**Comment by WASasquatch** [comment]
Image node can't have outputs or it breaks image viewing.

**Comment by Kiaazad** [comment]
How about just the name input, maybe we can handle the naming with a primitive node?
I'm not sure if the node has to check the other files in the folder before naming the file, maybe we can have a counter with some string function to generate a new name on each queue, then pass it to two image save nodes.

**Comment by WASasquatch** [comment]
> How about just the name input, maybe we can handle the naming with a primitive node? I'm not sure if the node has to check the other files in the folder before naming the file, maybe we can have a counter with some string function to generate a new name on each queue, then pass it to two image save nodes.

I think you're looking for the prefix_as_filename overwrite mode?

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/a6607c21-e6bb-485c-ad49-305f4e0c9d47)

**Comment by Kiaazad** [comment]
Oh, I assumed overwrite mode is for overwriting the files. With a counter it works almost flawlessly. The only hurdle I have is the counter resets and overwrites files when I relaunch comfyui.
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/33455007/8d1e9a28-c40f-446b-913e-5f1feef87f90)
Do you know of any node to check the folder and start the name right after the latest file? The save nodes seem to handle that part, maybe that functionality alongside setting folder names can be isolated?
Or better, a node that saves multiple images in different folders but with the same name?

**Comment by WASasquatch** [comment]
I don't. That's sorta the point of the prefix system is it detects that and
continues. You can define how many leading zeros it has, as well as if it
starts at end of beginning of filename_prefix

**Comment by Kiaazad** [comment]
Thank you, I think we can close this issue.
What do you think about the multi file save node idea? Is it feasible? Should I suggest it in a new issue?

**Comment by WASasquatch** [comment]
Multiple paths might be doable. I'll have to look to see how best to incorporate it if not another node.

**Comment by WASasquatch** [comment]
> Multiple paths might be doable. I'll have to look to see how best to incorporate it if not another node. Feel free to make a discussion request so I don't forget.
