### ISSUE TITLE
Missing nodes after updating

### ISSUE THREAD

**Issue by Rojinski** [WASasquatch/was-node-suite-comfyui#230]
Hello! 

After updating the WAS Node Suite, I can't use the workflows I could use until yesterday. :) I've updated everything (git pull), so I'm sure everything is up to date.  Other workflows are working fine if they don't use WAS or AIT (same pb with it with some nodes). I've even tried to "install missing nodes" with the ComfyUI Manager but it shows it as already installed.  But the cmd window says it was impossible to import the WAS node suite... 

` 0.0 seconds (IMPORT FAILED): D:\Programmes 2\Logiciels\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui`

I attach a screenshot of what I get. I hope someone can help me. Have a beautiful week-end !

![Screenshot 2023-10-06 at 14-58-56 ComfyUI](https://github.com/WASasquatch/was-node-suite-comfyui/assets/122015375/2f590603-23c3-40e0-bad9-9512ab5ce6dd)
![Screenshot 2023-10-06 at 15-08-33 ComfyUI](https://github.com/WASasquatch/was-node-suite-comfyui/assets/122015375/63d32a89-f794-4913-b4d0-ccb1a570e1e2)
![Screenshot 2023-10-06 at 15-33-57 ComfyUI](https://github.com/WASasquatch/was-node-suite-comfyui/assets/122015375/295abce2-70e9-4dfb-8b7c-7e699aebdeea)

**Comment by WASasquatch** [comment]
You often need to re-run requirements file to actually *finish* updating.

**Comment by Rojinski** [comment]
First of all, thanks to your fast answer. :) But how can I re-run requirement file?

**Comment by Rojinski** [comment]
> You often need to re-run requirements file to actually _finish_ updating.

First of all, thanks to your fast answer. :) But how can I re-run requirement file?

**Comment by WASasquatch** [comment]
You can try the install.bat if you using the Windows Portable version, or you have to run requirements through portables exe like `ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install -r "full path to was-node-suite-comfyui\requirements.txt"`

**Comment by Rojinski** [comment]
> You can try the install.bat if you using the Windows Portable version, or you have to run requirements through portables exe like `ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install -r "full path to was-node-suite-comfyui\requirements.txt"`
> 
> Usually there are errors above the import failure that tell you why exactly things are crashing.

The install.bat trick didn't work but the cmd did ! Thanks a lot for your help and your time !!!!
