### ISSUE TITLE
[suggestion] Drag-and-drop functionality for "WAS Image Load" node and “select image” button.

### ISSUE THREAD

**Issue by Ratinod** [WASasquatch/was-node-suite-comfyui#243]
The idea is simple: when you drag-and-drop an image over the "WAS Image Load" node, the previous "image_path" is automatically deleted and replaced with a new one (the full path of the used image).

I would also like a “select image” button that opens a standard explorer along the “image_path” path, allowing you to select an image (сhanges “image_path” to the path to the selected image.) in the standard way for your OS.

**Comment by WASasquatch** [comment]
This node is designed to load images from the net and entire PC. It's not compatible.

**Comment by Ratinod** [comment]
I had no idea about the functionality that allows you to download images from the net. In this case, the “select image” button really turns out to be inappropriate. I guess drag-and-drop will not work because there is no “image field” in the node (as in the original "Image Load" node)?
In that case, I have one last question: Is it possible to make it so that by default, when opening “image_path”, the entire previous specified path is highlighted? So that when you paste a path from clipboard, it is completely replaced and not added to the end of the previous one.

**Comment by WASasquatch** [comment]
> I had no idea about the functionality that allows you to load images from the net. In this case, the “select image” button really turns out to be inappropriate. I guess drag-and-drop will not work because there is no “image field” in the node (as in the original "Image Load" node)? In that case, I have one last question: Is it possible to make it so that by default, when opening “image_path”, the entire previous specified path is highlighted? So that when you paste a path from clipboard, it is completely replaced and not added to the end of the previous one.

That would be something to bring to ComfyUI as a feature request (highly value in field when opening it).

WAS-NS doesn't deploy any JS, and I don't want to, especially for something so small. Scripts seem to often cause problems with ComfyUI

**Comment by Ratinod** [comment]
> That would be something to bring to ComfyUI as a feature request (highly value in field when opening it).
> 
> WAS-NS doesn't deploy any JS, and I don't want to, especially for something so small. Scripts seem to often cause problems with ComfyUI

Understand. In this case, I will make a feature request in ComfyUI.
In any case, thanks for creating such a useful set of nodes.
