### ISSUE TITLE
Getting requirements to build wheel did not run sucessfully

### ISSUE THREAD

**Issue by Sensha563** [WASasquatch/was-node-suite-comfyui#244]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/148725780/0e570906-7157-4c72-895c-840b8f6aed72)
using the portable version of comfyui, happens when trying to install the requirements

**Comment by WASasquatch** [comment]
Assuming you are using nightly 3.12 python version, that version of countorpy isn't supported. I don't officially support 3.12.yet. though looking into it.

**Comment by Sensha563** [comment]
no i don't beleive have 3.12, the one in path is 3.10.6, i was under the impression it wouldn't matter since it's using the exe out of venv. i'll try taking the version requirements out

**Comment by Sensha563** [comment]
taking the version requirement for numpy out made it install, thanks
