### ISSUE TITLE
WAS Node Suite IMPORT FAILED

### ISSUE THREAD

**Issue by anuplohade** [WASasquatch/was-node-suite-comfyui#246]
### Discussed in https://github.com/WASasquatch/was-node-suite-comfyui/discussions/245

<div type='discussions-op-text'>

<sup>Originally posted by **anuplohade** October 23, 2023</sup>
WAS suite is failing to import into comfy ui suddenly and it seems CSV file has something to do with it.
CSV file format is correct and path is also added into 'was_suite_config.json'
Python Version: 3.10.6

Could anyone please help in resolving this issue?
(Please check screenshots for reference.)
![Screenshot 2023-10-23 225212](https://github.com/WASasquatch/was-node-suite-comfyui/assets/72828505/5f41533a-afbe-4527-b2f2-02fe6294f2f2)
![Screenshot 2023-10-23 225302](https://github.com/WASasquatch/was-node-suite-comfyui/assets/72828505/c70acf5e-7d9e-49a4-a82e-7984750a886e)
![Screenshot 2023-10-23 225352](https://github.com/WASasquatch/was-node-suite-comfyui/assets/72828505/98d86930-88ad-462f-b6fd-c90cde0ebc7a)
![Screenshot 2023-10-23 225425](https://github.com/WASasquatch/was-node-suite-comfyui/assets/72828505/dbb3cc7e-1f91-4786-9767-aeeae33a5ef1)
</div>

**Comment by anuplohade** [comment]
I was able to resolve it.

I had to change the line 309 in WAS_Node_Suite.py and rename it to the column heading of style from CSV file i.e. 'style_name'

Secondly I changed CSV file to UTF-8 encoding format.

**Comment by WASasquatch** [comment]
So what you're actually saying is that A1111 has updated it's format, to include "style_name" instead of "name".
