### ISSUE TITLE
[feature request] N Text concatenate

### ISSUE THREAD

**Issue by billbo100** [WASasquatch/was-node-suite-comfyui#260]
Is there anyway to modify Text Concatenate to allow a variable number of inputs? Would look much cleaner if there was a way to only have 2, or to have say 7 without having to chain these nodes together.

**Comment by WASasquatch** [comment]
That would be front end JS side and I am not deploying JS with WAS-NS currently. Pure python backend only right now.

**Comment by billbo100** [comment]
Fair enough. Saw a different custom node (ComfyUI_Dave_CustomNode) do something like it and didn't know how it was done. Taking a quick glance through the code I see that it is implemented in JS.

**Comment by billbo100** [comment]
Fair enough. Saw a different custom node (ComfyUI_Dave_CustomNode) do something like it and didn't know how it was done. Taking a quick glance through the code I see that it is implemented in JS.
