### ISSUE TITLE
I can't create a Load Batch Images node

### ISSUE THREAD

**Issue by ghost** [WASasquatch/was-node-suite-comfyui#272]
I don't see anything in my list of nodes that looks like `Load Batch Images`.

**Comment by WASasquatch** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/a05b1f1d-5231-4b8d-8c7b-7ca3ca5b0f8c)

It's under IO. You can also search nodes by double clicking the canvas background.

**Comment by somebush** [comment]
I don't have your nodes in the IO section, despite the fact that ComfyUI Manager shows WAS Node Suit installed. I can't delete or disable it through the manager.

**Comment by somebush** [comment]
![ui](https://github.com/WASasquatch/was-node-suite-comfyui/assets/132480428/1c67bdff-efdb-4e76-a8c5-ef3cc15d99db)
after installing your add-on, these nodes did not appear in the IO section

**Comment by WASasquatch** [comment]
You don't seem to have WAS Node Suite installed at all.
