### ISSUE TITLE
update requirements.txt

### ISSUE THREAD

**Issue by Khazar123** [WASasquatch/was-node-suite-comfyui#279]
This node suite is great, but every update through the manager installs the old transformers and it's dependencies.

Would it be possible to check, if the requirements.txt can get an updated version? I've had 0 problems since months now using this with the newest transformers and it's dependencies on the newest updates too.

Thank you for this project and all the work you put into it!

**Comment by WASasquatch** [comment]
Those are requirements, for things like MiDaS and BLIP.
