### ISSUE TITLE
Wildcard Issue

### ISSUE THREAD

**Issue by Yggdrasil777** [WASasquatch/was-node-suite-comfyui#28]
![image](https://user-images.githubusercontent.com/775705/229870160-1188ee74-7140-4d4a-8d8b-aac681368a40.png)

results in this

![image](https://user-images.githubusercontent.com/775705/229870300-3a6aa6d3-ace2-463b-853b-fe84c4d911a3.png)

It does not seem to be loading the text file, or it will load in the last text file in the chain and cannot replace correctly?

![image](https://user-images.githubusercontent.com/775705/229871313-6ee0c976-dcb8-4506-b7b9-b52170026113.png)

Prompt: "\__color__ color, \__costume__ expression, detailed skin"
Console Result: " expression, detailed skinme" (without the quotes, notice the leading space)

The full prompt results in this output:
![image](https://user-images.githubusercontent.com/775705/229872122-025efb24-9fcc-4ae2-9894-049e3e61b9dd.png)

![image](https://user-images.githubusercontent.com/775705/229874294-e12d52d6-a59f-4d14-b142-1d7153a71f02.png)

I have produced a node structure highlighting the degradation of the prompt line by line:

![image](https://user-images.githubusercontent.com/775705/229875288-10acd304-1344-44d0-b1b6-c0a02fed2e58.png)

![image](https://user-images.githubusercontent.com/775705/229875100-4386147d-ab94-4e76-9827-d474f9222dc1.png)

Also, it seems to be truncating the fed in info as well:
![image](https://user-images.githubusercontent.com/775705/229877692-f84a26e4-fcab-4d42-a51b-74013126415b.png)

![image](https://user-images.githubusercontent.com/775705/229877412-39b00b82-8db9-4750-9fe1-e163a99dff0b.png)

Notice the difference between the WAS output and the console string output.

A formatted look:
![image](https://user-images.githubusercontent.com/775705/229879030-925e621e-bbec-41df-9066-36d55c8e8061.png)

from this:
![image](https://user-images.githubusercontent.com/775705/229879178-9328c0cd-b9f7-4333-bd24-a94215904097.png)

**Comment by Yggdrasil777** [comment]
Attached to this is the .json so that you can drag it onto ComfyUI without having to set all of this up yourself.
[workflow (22).zip](https://github.com/WASasquatch/was-node-suite-comfyui/files/11151438/workflow.22.zip)

**Comment by WASasquatch** [comment]
Probably an issue with the regrx replacement. Thanks for the workflow and console logs.

**Comment by Yggdrasil777** [comment]
I did discover that breaking the noodles onto their own lines did the expected results, but it really takes up a lot of room.
![image](https://user-images.githubusercontent.com/775705/229893494-873956e1-29d3-468e-83c5-41b8b044ad74.png)

![image](https://user-images.githubusercontent.com/775705/229893615-8a929690-da35-44e2-ba36-1a5946a3f309.png)

**Comment by WASasquatch** [comment]
> I did discover that breaking the noodles onto their own lines did the expected results, but it really takes up a lot of room. ![image](https://user-images.githubusercontent.com/775705/229893494-873956e1-29d3-468e-83c5-41b8b044ad74.png)
> 
> ![image](https://user-images.githubusercontent.com/775705/229893615-8a929690-da35-44e2-ba36-1a5946a3f309.png)

That's... kinda odd. I think it's cause I thought I was clever and going to use regex which should be faster at finding things in a string, but failed to realize how this specifically works in Python (it does seem a bit different than regular expression parsers I've used in say PHP/Java)

Maybe I should just rewrite it like the NSP parser.

**Comment by Yggdrasil777** [comment]
As a side note, the layout gets borked when you load it into ComfyUI.
That might be a ComfyUI issue, though. Try it and see if you get the same problem.

**Comment by WASasquatch** [comment]
NSP is what *most* the wildcard default files are based on. They converted my project to individual files instead of a JSON database (for easier editing, instead of designing a webui interface to load database and add/remove/view). 

So it contains most everything you're already using, though may be named differently: https://github.com/WASasquatch/noodle-soup-prompts/wiki/Terminology-Reference

**Comment by WASasquatch** [comment]
A patch is in for the input replacement.

**Comment by WASasquatch** [comment]
New method for loading wildcards: https://github.com/WASasquatch/was-node-suite-comfyui/tree/main/workflows#wildcards-from-load-text-file-dictionary

(Same Workflow from link)
![Wildcards_with_Dictionary_Text_File](https://user-images.githubusercontent.com/1151589/229928623-d57a05d1-1224-4fa2-85b3-6cd3ecb2aa86.png)

This should be a lot more flexible.

**Comment by Yggdrasil777** [comment]
Just an FYI:
![image](https://user-images.githubusercontent.com/775705/230744491-37c8387a-09d1-43d2-9854-1b26c2991805.png)

My fix:
![image](https://user-images.githubusercontent.com/775705/230744535-9d7d15a0-ca20-4c21-ae0c-0f04521cd182.png)
![image](https://user-images.githubusercontent.com/775705/230744544-50b8b63f-2244-4fc6-9df9-dce87da0d255.png)

**Comment by WASasquatch** [comment]
It should now be just using `os.path.join(WAS_SUITE_ROOT, 'nsp_pantry.json')` Hasn't been updated for colab support or downloading directly
