### ISSUE TITLE
Adding WAS nodes breaks Generate button until browser refresh

### ISSUE THREAD

**Issue by poisenbery** [WASasquatch/was-node-suite-comfyui#285]
When I add these nodes from your suite, the Generation button stops working until I refresh the browser page.
It's usually with Text to Conditioning nodes/Text Multiline.

**Comment by poisenbery** [comment]
I think I have steps to replicate:

1.) Use a text multi-line node + "Text to Conditioning" to set up some sampler. Generate some images
2.) Duplicate the "text to conditioning" node. When you connect the "String" output from the multi-line, comfyUI should soft lock. The generation button will not work, neither will save/load functions.

**Comment by WASasquatch** [comment]
This is a ComfyUI front-end bug. Report there.
