### ISSUE TITLE
Batch img load Vram???

### ISSUE THREAD

**Issue by Echolink50** [WASasquatch/was-node-suite-comfyui#286]
Not sure what I'm doing wrong but comfyui tries to load all the images from the folder at once. It's fine for 200 or so images but larger batches run out of Vram. How can the batch loader process the images one at a time? I have a ln RTX 2060 12GB. Am I missing something? Thanks everyone.

**Comment by WASasquatch** [comment]
Load Image Batch only ever loads one image whether in single image mode or
incremental. You use multiple prompt batches to increment through them.
