### ISSUE TITLE
[Feature Request] Image Scale by Factor

### ISSUE THREAD

**Issue by throwaway-mezzo-mix** [WASasquatch/was-node-suite-comfyui#3]
First of all, thank you for providing these incredibly useful nodes.
I am a big fan of the Latent Upscale by Factor node as it saves some annoying fiddling after you adjust the starting resolution in an Latent Upscale workflow.

Sometimes, I throw the resulting image into an regular Upscaler (like 4x-UltraSharp). The resolution that results in is often way too big, so I downscale using the default ImageScale Node. However, I have to adjust the resolution manually here whenever I change the starting resolution of my workflow.

Having an Factor version (one that could also downscale) of the ImageScale Node would be really useful.

**Comment by WASasquatch** [comment]
You can just use something like `0.5` on your input for 4x, which would give you 2x. ;)

**Comment by throwaway-mezzo-mix** [comment]
Oh, I didn't even think about using the Latent factor upscale AFTER the second sampler node. I guess I was focused on modifying an already decoded image because I was saving the pre-upscale versions.
Now I feel a bit silly, thanks for the help.

(This is what you meant, right?)
![upscale](https://user-images.githubusercontent.com/110428425/227701410-3641d318-c7f5-4bcf-8e9c-4359e1c9377f.png)

**Comment by WASasquatch** [comment]
Yeah just like that, though I assume you know the latent upscale doesn't generate a image :P

**Comment by throwaway-mezzo-mix** [comment]
> Yeah just like that, though I assume you know the latent upscale doesn't generate a image :P
yeah that was just an example i quickly made because my real work flow is a bit of a mess lol

>Oh, wait no, you'd want to scale down after upscale. Though though that may work as well, but may result in quality loss cause up-scaling from a smaller image.
that would mean i would have to do something like this to be able to only use a factors instead of hard values:
![upscale2](https://user-images.githubusercontent.com/110428425/227702611-e59717d7-6d2d-4982-985f-9b23009adde3.png)
i was worried that encoding and decoding like this might have some adverse affects (which is why i asked for an image scale by factor in the first place), but i have no idea if that's actually the case.

**Comment by WASasquatch** [comment]
It could very well, though I haven't noticed myself. Perhaps it's time for a regular image scale by factor/resize

**Comment by throwaway-mezzo-mix** [comment]
I did just find another reason an regular image scale might be a good inclusion, VRAM usage.
![OOM](https://user-images.githubusercontent.com/110428425/227703756-5e71626c-7c24-40a1-a665-b9d66f335658.png)

**Comment by throwaway-mezzo-mix** [comment]
using the tiled vae nodes i was able to actually go through the process, but the image ended up being pretty messed up. (the image was fine after scaling with ultrasharp, so it must have either been the (tiled) encoding/decoding or the downscale)

[4x ultrasharp here, was too big for github](https://files.catbox.moe/2k46in.png)
![after downscale](https://user-images.githubusercontent.com/110428425/227704976-6e99b09e-462c-46cc-932d-dede670e3f64.png)

**Comment by WASasquatch** [comment]
I have a image resize ready, and a transpose, going to add padding and couple other. Probably release tomorrow morning at some point. It's 1:20 here and almost too tired to shower haha

**Comment by throwaway-mezzo-mix** [comment]
that's awesome. thanks for all the help.

**Comment by WASasquatch** [comment]
> that's awesome. thanks for all the help.

Image resize should be in. Little busy today, hopefully it's all good.
