### ISSUE TITLE
Int to number node doesn't work

### ISSUE THREAD

**Issue by lcolok** [WASasquatch/was-node-suite-comfyui#30]

**Comment by WASasquatch** [comment]
See: https://github.com/comfyanonymous/ComfyUI/issues/368#issuecomment-1498003825

Maybe voice your opinion on how this is considered a bug to randomly not allow certain types as input only.

**Comment by WASasquatch** [comment]
These are removed until the issue is resolved.

**Comment by lcolok** [comment]
> These are removed until the issue is resolved.

This is a pity, because I was hoping to build a workflow that could read the size of incoming images and match them with corresponding empty latents for image generation and other operations.

**Comment by WASasquatch** [comment]
> > These are removed until the issue is resolved.
> 
> This is a pity, because I was hoping to build a workflow that could read the size of incoming images and match them with corresponding empty latents for image generation and other operations.

Well there is no node to get the width/height of a image and pass it along, but the rest of the functionality is already there if it were, such as `Number to Int` to then plug into a EmptyLatent.

**Comment by WASasquatch** [comment]
I added a Image Size to Number node in 2ff0c04a656d1d69f8eb24d76159dfd8cbf59a04

**Comment by lcolok** [comment]
> I added a Image Size to Number node in [2ff0c04](https://github.com/WASasquatch/was-node-suite-comfyui/commit/2ff0c04a656d1d69f8eb24d76159dfd8cbf59a04)
> 
> I'll add a latent one later.

That's really helpful for my workflow! I appreciate your efforts and I'm looking forward to seeing the latent one as well.
