### ISSUE TITLE
[Feature] Add "Choose File to Upload" button (like other image loaders)

### ISSUE THREAD

**Issue by ghostsquad** [WASasquatch/was-node-suite-comfyui#324]
Please add a "Choose file to upload" button like other loaders. The nice part about _this_ loader is that it exports the path of the image loaded. Other loaders don't do that.

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/903488/b6ad6eb3-00ed-414b-9d98-931eb347793a)

**Comment by WASasquatch** [comment]
I am not adding any JavaScript to WAS-NS. I, as well as many services use it headless without a GUi for API.

**Comment by ghostsquad** [comment]
Ah. I'll reach out to another author and see if they can export the checkpoint path. Thanks for the explanation.

**Comment by WASasquatch** [comment]
> Ah. I'll reach out to another author and see if they can export the checkpoint path. Thanks for the explanation.

If you can do it via extending nodes that already have file upload, like load image in base ComfyUI and do a PR, that's fine.
