### ISSUE TITLE
Cannot import ,  returned non-zero exit status 2

### ISSUE THREAD

**Issue by msskaa12** [WASasquatch/was-node-suite-comfyui#327]
Thanks for this awesome work ,buddy ！

after install , error message popup. how can I fix this problem, appreciate any help 

I had mannully install requirements.txt

OS:ubuntu 20.04
python: 3.10
comfyui: had update newest

![Screenshot from 2024-01-10 21-54-13](https://github.com/WASasquatch/was-node-suite-comfyui/assets/78275037/b80de086-8704-4065-a45f-6d9fb8bc9bf8)

**Comment by msskaa12** [comment]
fix it by : 

1 install mercurial :  sudo apt-get install mercurial
2 Clean up Pip Cache: python -m pip cache purge

**Comment by WASasquatch** [comment]
Do you know what package wanted to install mercurial, or if this is Linux/Ubuntu specific?
