### ISSUE TITLE
Error with Load Image Batch node

### ISSUE THREAD

**Issue by dheidenr1** [WASasquatch/was-node-suite-comfyui#338]
I receive the following error when trying to use the load image batch node:

![ImageLoaderError](https://github.com/WASasquatch/was-node-suite-comfyui/assets/131724702/5f108ce5-d225-47d1-b9c7-bfbf07b4a48d)

The node worked for a short time while using it today and then ceased working. Any advice would be appreciated.

**Comment by dheidenr1** [comment]
Figured it out. I think the file that contains the history got too full and as a result was no longer formatted properly. Manually reformatting the file (ie adding proper punctuation) seems to have fixed it.

**Comment by WASasquatch** [comment]
I've noticed with python,  sometimes JSON files just get corrupted. It literally happened to me twice with a Gradio app today. And first time took me forever to figure out cause they had the error exception wrong and lead me astray. Lol but yeah not sure why. I think it's the saving logic, getting interrupted somehow or something.
