### ISSUE TITLE
Got Error When Using Text Dictionary Update node.

### ISSUE THREAD

**Issue by BoosterCore** [WASasquatch/was-node-suite-comfyui#34]
![微信图片_20230407151923](https://user-images.githubusercontent.com/73834045/230561947-df52a539-9366-4c3d-affc-d88ef6253e94.png)
![微信图片_20230407151927](https://user-images.githubusercontent.com/73834045/230561964-67c96f28-c006-4113-82af-78b4134ffffb.png)

**Comment by BoosterCore** [comment]
condition 4
![微信图片_20230407150242](https://user-images.githubusercontent.com/73834045/230559271-624c3e8f-7d9e-4edf-9f31-d81669801565.png)
![微信图片_20230407150245](https://user-images.githubusercontent.com/73834045/230559293-add8881c-3e9e-461b-8611-4152f07df4e0.png)

**Comment by BoosterCore** [comment]
Here is my wildcard file
[Overall Style.txt](https://github.com/WASasquatch/was-node-suite-comfyui/files/11176795/Overall.Style.txt)

**Comment by WASasquatch** [comment]
That should be patched now. I figured you could just check `if dictionary_c:` but apparently it's returning true as "None" and thus attempting to merge it. Weird. It's not ensuring it's not `None`.

**Comment by BoosterCore** [comment]
Text Find and Replace by Dictionary not working now:
![微信图片_20230407162854](https://user-images.githubusercontent.com/73834045/230573403-c5234a6c-1c20-4f0f-a115-940cb2342af6.png)
![微信图片_20230407162858](https://user-images.githubusercontent.com/73834045/230573418-07b07301-2676-4712-9665-72a0cfb0eaa0.png)

**Comment by BoosterCore** [comment]
![微信图片_20230407164240](https://user-images.githubusercontent.com/73834045/230575637-ffb38bcf-c3ea-465a-9ec0-9f416fc00da9.png)
![微信图片_20230407164243](https://user-images.githubusercontent.com/73834045/230575652-3df8b053-cee1-475f-a4ec-190c2877f4b8.png)

**Comment by BoosterCore** [comment]
![微信图片_20230407170017](https://user-images.githubusercontent.com/73834045/230578757-d0b01e8a-9eb6-4fca-80b2-d3c513552db6.png)
`got prompt
WAS Node Suite Dictionary Output:

{   '[OverallStyle1]': [   'sci-fi\r',
                           'futuristic\r',
                           'cyberpunk\r',
                           'fantasy\r',
                           'steam punk\r',
                           'atompunk\r',
                           'diesel punk\r',
                           'gothic\r',
                           'chinese ancient\r',
                           'baroque\r',
                           'dystopian\r',
                           'islamic\r',
                           'middle eastern\r',
                           'african\r',
                           'south american'],
    '[OverallStyle2]': [   'sci-fi\r',
                           'futuristic\r',
                           'cyberpunk\r',
                           'fantasy\r',
                           'steam punk\r',
                           'atompunk\r',
                           'diesel punk\r',
                           'gothic\r',
                           'chinese ancient\r',
                           'baroque\r',
                           'dystopian\r',
                           'islamic\r',
                           'middle eastern\r',
                           'african\r',
                           'south american'],
    '[OverallStyle3]': [   'sci-fi\r',
                           'futuristic\r',
                           'cyberpunk\r',
                           'fantasy\r',
                           'steam punk\r',
                           'atompunk\r',
                           'diesel punk\r',
                           'gothic\r',
                           'chinese ancient\r',
                           'baroque\r',
                           'dystopian\r',
                           'islamic\r',
                           'middle eastern\r',
                           'african\r',
                           'south american'],
    '[OverallStyle4]': [   'sci-fi\r',
                           'futuristic\r',
                           'cyberpunk\r',
                           'fantasy\r',
                           'steam punk\r',
                           'atompunk\r',
                           'diesel punk\r',
                           'gothic\r',
                           'chinese ancient\r',
                           'baroque\r',
                           'dystopian\r',
                           'islamic\r',
                           'middle eastern\r',
                           'african\r',
                           'south american']}

WAS Node Suite Text Output:
__OverallStyle1__ and __OverallStyle2__ environment concept design,__OverallStyle3__ and __OverallStyle4__`

**Comment by WASasquatch** [comment]
Your files are messed up and not using \n for some reason. I'll have to add a check to convert the file

**Comment by WASasquatch** [comment]
> ![微信图片_20230407170017](https://user-images.githubusercontent.com/73834045/230578757-d0b01e8a-9eb6-4fca-80b2-d3c513552db6.png) `got prompt WAS Node Suite Dictionary Output:
> 
> { '[OverallStyle1]': [ 'sci-fi\r', 'futuristic\r', 'cyberpunk\r', 'fantasy\r', 'steam punk\r', 'atompunk\r', 'diesel punk\r', 'gothic\r', 'chinese ancient\r', 'baroque\r', 'dystopian\r', 'islamic\r', 'middle eastern\r', 'african\r', 'south american'], '[OverallStyle2]': [ 'sci-fi\r', 'futuristic\r', 'cyberpunk\r', 'fantasy\r', 'steam punk\r', 'atompunk\r', 'diesel punk\r', 'gothic\r', 'chinese ancient\r', 'baroque\r', 'dystopian\r', 'islamic\r', 'middle eastern\r', 'african\r', 'south american'], '[OverallStyle3]': [ 'sci-fi\r', 'futuristic\r', 'cyberpunk\r', 'fantasy\r', 'steam punk\r', 'atompunk\r', 'diesel punk\r', 'gothic\r', 'chinese ancient\r', 'baroque\r', 'dystopian\r', 'islamic\r', 'middle eastern\r', 'african\r', 'south american'], '[OverallStyle4]': [ 'sci-fi\r', 'futuristic\r', 'cyberpunk\r', 'fantasy\r', 'steam punk\r', 'atompunk\r', 'diesel punk\r', 'gothic\r', 'chinese ancient\r', 'baroque\r', 'dystopian\r', 'islamic\r', 'middle eastern\r', 'african\r', 'south american']}
> 
> WAS Node Suite Text Output: **OverallStyle1** and **OverallStyle2** environment concept design,**OverallStyle3** and **OverallStyle4**`

Try the latest patch. Attempting to cover all linebreak scenarios.

**Comment by BoosterCore** [comment]
Still the same error as before
[Overall Style.txt](https://github.com/WASasquatch/was-node-suite-comfyui/files/11182405/Overall.Style.txt)

**Comment by WASasquatch** [comment]
> Still the same error as before [Overall Style.txt](https://github.com/WASasquatch/was-node-suite-comfyui/files/11182405/Overall.Style.txt)

You must not have updated correctly:

![Screenshot_51](https://user-images.githubusercontent.com/1151589/230705187-d1c43db2-16b1-4679-aead-bce6a2e1ce37.png)
![Screenshot_52](https://user-images.githubusercontent.com/1151589/230705189-ba9a2e90-209c-4a55-b85b-b83827661a19.png)

**Comment by BoosterCore** [comment]
Thank U，It is working now！

**Comment by WASasquatch** [comment]
> > Still the same error as before [Overall Style.txt](https://github.com/WASasquatch/was-node-suite-comfyui/files/11182405/Overall.Style.txt)
> 
> You must not have updated correctly:
> 
> ![Screenshot_51](https://user-images.githubusercontent.com/1151589/230705187-d1c43db2-16b1-4679-aead-bce6a2e1ce37.png) ![Screenshot_52](https://user-images.githubusercontent.com/1151589/230705189-ba9a2e90-209c-4a55-b85b-b83827661a19.png)
