### ISSUE TITLE
Is it possible to develop such functionality？

### ISSUE THREAD

**Issue by BoosterCore** [WASasquatch/was-node-suite-comfyui#35]
Is it possible to develop such functionality？
It allows users to create a node and add various output ports to it to drive various parameters scattered on other nodes, just like in Substance Designer.
With such a function, when a procedural workflow is created, various important parameters can be adjusted intuitively and quickly in just one node, without having to search through many nodes.

**Comment by WASasquatch** [comment]
I don't know what you mean. Comfy already allows you to convert any field on a node into a input, then you use a Primitive from utils and it will transform into a Int or Float, etc.

**Comment by BoosterCore** [comment]
I see what you mean, and I tried it, it works, thank you very much!
Is it possible to put all these Primitives into a custom node?

**Comment by WASasquatch** [comment]
> I see what you mean, and I tried it, it works, thank you very much! Is it possible to put all these Primitives into a custom node?

The primitive node is a web front side node, not a python node. That's how it automatically detects what type of input it should be and transforms itself accordingly.
