### ISSUE TITLE
TypeError: WAS_Boolean.return_boolean() got an unexpected keyword argument 'boolean_number'

### ISSUE THREAD

**Issue by jerrydavos** [WASasquatch/was-node-suite-comfyui#351]
Hello Author,

The last commit broke the Logic Boolean Node: 

```
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: WAS_Boolean.return_boolean() got an unexpected keyword argument 'boolean_number'

Prompt executed in 0.00 seconds

```
![20240301_151403](https://github.com/WASasquatch/was-node-suite-comfyui/assets/152957217/c5f1a00b-5f1b-4167-a8e5-5892c7f8e566)

Thanks for your nodes, Love them,
it's very much used in all of my workflows <33

**Comment by Chryseus** [comment]
Yep same problem here.

**Comment by whmc76** [comment]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WAS_Boolean.return_boolean() got an unexpected keyword argument 'boolean_number'

same here

**Comment by HEYVVV** [comment]
same problem here.

**Comment by aegis72** [comment]
Same here as well

**Comment by Ionaut** [comment]
Check these in custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/8879570/873b428b-7178-440e-bf99-5ca5367a9daa)

**Comment by alenknight** [comment]
> Check these in custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py ![image](https://private-user-images.githubusercontent.com/8879570/317482946-873b428b-7178-440e-bf99-5ca5367a9daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTM5ODMsIm5iZiI6MTcxMTc1MzY4MywicGF0aCI6Ii84ODc5NTcwLzMxNzQ4Mjk0Ni04NzNiNDI4Yi03MTc4LTQ0MGUtYmY5OS01Y2E1MzY3YTlkYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMjMwODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWI4MGQ4MzU5NGI4NTYxY2ZhOTFjZjgwZWJlZDM4YjMwYzQxZGFjY2EzMjhkMTEwZjM1NTY3YWI0ZDg5ZmZkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YVqdgE-3zvVzD2othZkoyjNi_aVcR7oc4SQwJtZSP9Q)

mine matches what you have on the screenshare,.... but still same error.

**Comment by dafeng012** [comment]
> 在 custom_nodes\was-node-suite-comfyui\ 中检查这些内容WAS_Node_Suite.py ![image](https://private-user-images.githubusercontent.com/8879570/317482946-873b428b-7178-440e-bf99-5ca5367a9daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjUxMzgsIm5iZiI6MTcxMjA2NDgzOCwicGF0aCI6Ii84ODc5NTcwLzMxNzQ4Mjk0Ni04NzNiNDI4Yi03MTc4LTQ0MGUtYmY5OS01Y2E1MzY3YTlkYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMTMzMzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzlkMzMwZWUxNzZiOGRiYTkwMWVhMjI4YTZhMjBhN2FjOWNiY2I3NDIyZWEwYjI5MjBlMWM1M2Y2MmQ5Y2JmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p39CHYZC-BNBRajldstQfVDfFPQxhlRMFBqs40Eac0M)
并不能解决问题

**Comment by jerrydavos** [comment]
Update to the latest version, this error will be fixed

**Comment by jmux** [comment]
Fully updated today. Getting this same error. 

`Error occurred when executing Number Input Switch:

WAS_Number_Input_Switch.number_input_switch() got an unexpected keyword argument 'boolean_number'

File "M:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "M:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "M:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by WAS-PlaiLabs** [comment]
The node no longer uses `boolean_number`. It uses `boolean`, a regular boolean widget. Update the node itself. 

```
# NUMBER INPUT SWITCH

class WAS_Number_Input_Switch:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "number_a": ("NUMBER",),
                "number_b": ("NUMBER",),
                "boolean": ("BOOLEAN", {"forceInput": True}),
            }
        }

    RETURN_TYPES = ("NUMBER", "FLOAT", "INT")
    FUNCTION = "number_input_switch"

    CATEGORY = "WAS Suite/Logic"

    def number_input_switch(self, number_a, number_b, boolean=True):

        if boolean:
            return (number_a, float(number_a), int(number_a))
        else:
            return (number_b, float(number_b), int(number_b))
```
