### ISSUE TITLE
Can pictures be stitched together?

### ISSUE THREAD

**Issue by NO13Listener** [WASasquatch/was-node-suite-comfyui#37]
Picture a and picture b are put together (up and down/left and right or custom location)？
![1_00001_](https://user-images.githubusercontent.com/125913223/230735574-13706cd7-a02a-4b4d-8c1a-11a1a9e3337f.png)
![2_00001_](https://user-images.githubusercontent.com/125913223/230735581-df9eb6cf-2485-4691-b103-12c25a6b8c0f.png)
![END_00002_](https://user-images.githubusercontent.com/125913223/230735551-c2a0c2c9-8dd8-49ab-88a6-f1c67767011a.png)
like this，I can indeed do such stitching but now I need to add more complicated things to stitch three pictures，If it is added on the left or right of the picture, it seems more troublesome, and my operation will have great restrictions

**Comment by NO13Listener** [comment]
A total of three pictures, probably like this
You can drag the last big picture into the program to have a look

**Comment by WASasquatch** [comment]
Image padding and blend by mask.

**Comment by WASasquatch** [comment]
I've adding a stitching node to do exclusively what you were asking. I'll be adding it today.

Here is the result from the bode stitching "image_b" onto the bottom of "image_a"
![230735551-c2a0c2c9-8dd8-49ab-88a6-f1c67767011a](https://user-images.githubusercontent.com/1151589/230966963-65002e63-707b-4c6f-bc9b-98ebbd1347b8.png)
