### ISSUE TITLE
[Feature] Token Creation Node

### ISSUE THREAD

**Issue by wyrde** [WASasquatch/was-node-suite-comfyui#39]
As is, the functionality of tokens in the _Save Text File_ and _Save Image_ nodes is really useful. I think adding ability to define a token through the workflow will have profound impact.

Consider an ASCII to _Token Create_ node similar to concatenate. One ascii input sets the token name and the other sets the token definition. Then the _Text Parse Token_ node can be used to parse many of these dynamically created tokens. Users can use this to create dynamic save image paths/prefixes using other parts of their workflow.

The use case that gave me this idea: ![workflow with lots of random lists](https://github.com/wyrde/wyrde-comfyui-workflows/blob/main/why-oh-why/random-prompt-hrf-20img-output/workflow%20large.png). Currently it has random text lists and strings that go through 8 concatenate nodes to produce a prompt at the end. If I could generate tokens from the random lists, it would greatly simplify the prompt creation.

(In this use case, I'm deliberately avoiding _Text Parse Noodle Soup Prompts_ since I want everything contained in the workflow written to images without extra files.)

**Comment by WASasquatch** [comment]
Added in 2ff0c04a656d1d69f8eb24d76159dfd8cbf59a04

![image](https://user-images.githubusercontent.com/1151589/230796906-60362d81-4169-4ffb-b134-60adc733a3ae.png)
