### ISSUE TITLE
About stacking LORAS

### ISSUE THREAD

**Issue by alonsojr1980** [WASasquatch/was-node-suite-comfyui#391]
First of all, thanks for the nodes! What's the point of stacking LORAs if you can't use NONE in none of them? When setted to NONE, the node should output the unmodified inputs MODEL and CLIP. That would be an useful stacking. Thanks!

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/13320570/6f115c30-9a2d-49fa-8911-f23a1646079d)

**Comment by WAS-PlaiLabs** [comment]
I don't have a Lora Stacker? That's a Lora Loader, just like the base ComfyUI lora loader, which also, has no `None`. The only difference is it outputs the name of the lora.

**Comment by alonsojr1980** [comment]
Every node can be stacked, mate. The ComfyUI lora loader has no None, but it outputs the unchanged input when strength is zero. Your node should do the same when None is selected. I have made one of my own.

**Comment by WAS-PlaiLabs** [comment]
That's, just hooking nodes up. There are actual "Lora stacker" nodes. And this is Comfy's code. So set strength to 0? I'll see if he made changes.

**Comment by alonsojr1980** [comment]
Mate, "lora stacker" is nothing but "hooked nodes", each one processing the data and passing it to the next lora in the chain. Here is the LORA STACKER piece of code. They made it only to save us time, so we don't have to "hook" (STACK) them manually:

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/13320570/29b9cd09-f26c-49a9-97ea-2f568156ccd2)

**Comment by alonsojr1980** [comment]
I fixed it myself, never mind.

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/13320570/60b9ec11-2995-4e03-bc64-50f7a96dea5e)
