### ISSUE TITLE
DPI settings don't seem to apply.

### ISSUE THREAD

**Issue by Neytiri7** [WASasquatch/was-node-suite-comfyui#397]
I set the dpi to 300 on the image save node, but the actual image is saved as 72 dpi.

Is that option not applicable?

![noname](https://github.com/WASasquatch/was-node-suite-comfyui/assets/139053327/554c082d-87cd-48a2-a2b1-524dd64a5501)

**Comment by WAS-PlaiLabs** [comment]
Only works for JPEG pretty sure. It was a recent PR.

**Comment by Neytiri7** [comment]
Yes, sir. I'll use it to make it into JPG.
