### ISSUE TITLE
No WAS Suite menu found, where can I see it please?

### ISSUE THREAD

**Issue by terryxxxxx** [WASasquatch/was-node-suite-comfyui#4]
No WAS Suite menu found, where can I see this menu
I have extracted the file to /ComfyUI/custom_nodes/ folder

**Comment by WASasquatch** [comment]
You should be able to just extract to `/ComfyUI/custom_nodes/WAS_Node_Suite.py`

If you extracting to `custom_nodes` with `__init__.py` and not inside `was-node-suite-comfyui` folder, it probably won't work. 

What does your console say?

**Comment by AceroMagico** [comment]
if  extracted to /ComfyUI/custom_nodes/WAS_Node_Suite.py I can confirm that No WAS Suite menu is found.
However, if you extract into  '/ComfyUI/custom_nodes/was-node-suite-comfyui' and rename WAS_Node_Suite.py to __init__.py the menu appears and works.

**Comment by WASasquatch** [comment]
Strange. It works fine for me. I don't use any init nonsense or folders.

**Comment by AceroMagico** [comment]
I think I have uncovered the mystery , if you use the downloadable portable version it works as you say, if you use a version that uses the automatic1111 core for dependencies then you have to do as I wrote before : https://github.com/comfyanonymous/ComfyUI#i-already-have-another-ui-for-stable-diffusion-installed-do-i-really-have-to-install-all-of-these-dependencies

**Comment by WASasquatch** [comment]
> I think I have uncovered the mystery , if you use the downloadable portable version it works as you say, if you use a version that uses the automatic1111 core for dependencies then you have to do as I wrote before (but there's not a preexisting `__init__.py` it's just your .py renamed) : https://github.com/comfyanonymous/ComfyUI#i-already-have-another-ui-for-stable-diffusion-installed-do-i-really-have-to-install-all-of-these-dependencies

That is strange. I wonder why it can't load them normally. It doesn't sound like a dependency issue since it checks its own dependencies and installs if needed, which though would install to whatever venv is running it. But they are not forcing reinstalls or anything and should just skip.

**Comment by AceroMagico** [comment]
yes I think you are right : a dependency issue, auto1111 is a code that is always being modified and it is normal to have these problems...  for this reason I think I will switch to using ComfyUI in portable mode not in auto1111 mode, however renaming the -py is no big deal if one wanted to use the version that uses auto1111.

**Comment by WASasquatch** [comment]
> yes I think you are right : a dependency issue, auto1111 is a code that is always being modified and it is normal to have these problems... for this reason I think I will switch to using ComfyUI in portable mode not in auto1111 mode, however renaming the -py is no big deal if one wanted to use the version that uses auto1111.

Yeah. I haven't actually used WebUI in a couple weeks now. Been using ComfyUI.

**Comment by throwaway-mezzo-mix** [comment]
personally, i use the regular comfy version (not the portable one) using the same venv as automatic1111 and it works without problems. 
i installed it by cloning the entire folder into custom_nodes.
automatic1111 had a big update recently which i haven't pulled yet, so maybe that broke something?

**Comment by WASasquatch** [comment]
> personally, i use the regular comfy version (not the portable one) using the same venv as automatic1111 and just works™. i installed it by cloning the entire folder into custom_nodes. (so my file structure is \custom_nodes\was-node-suite-comfyui\<files>)
> 
> automatic1111 had a big update recently which i haven't pulled yet, so maybe that broke something?

That could be. I updated a couple weeks ago, so may have missed it. I always have issues with the updates. Especially reordering whole main menu all the time for seemingly no reason.

Hopefully it's a minor thing, though luckily there are multiple install methods.

**Comment by AceroMagico** [comment]
Yes I saw, you did well.
