### ISSUE TITLE
The preview image is displayed in the Image Save node as broken.

### ISSUE THREAD

**Issue by Neytiri7** [WASasquatch/was-node-suite-comfyui#403]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/139053327/719b3407-5e44-44ce-ab56-ea8ca4a241d5)

After the update, the preview image of the node is broken and displayed.

**Comment by WAS-PlaiLabs** [comment]
Delete and recreate the nodes.

**Comment by Neytiri7** [comment]
I deleted and re-placed the image save node, but the same error occurred.

I deleted the complete 'was' and reinstalled it, but it's the same.

**Comment by WAS-PlaiLabs** [comment]
Interesting. I can't reproduce in my desktop, laptop, or on Google vertex.
Only thing that change don the node was adding a DPI setting and optimize,
both have nothing to do with showing images.

**Comment by Neytiri7** [comment]
It's interesting for me too. I suddenly saw it coming out like that after the update...

I don't know if there's a problem with the connection node...
I need to test more to see if there is a problem with the setting of the dpi side.

**Comment by WAS-PlaiLabs** [comment]
Do you know what custom node this was? I know I heard of a pack that was using same class names as me, but the person never responded who which pack it was.

**Comment by Neytiri7** [comment]
https://github.com/portu-sim/comfyui_bmab

This is the custom node.
A folder is automatically created in output,
As a result, the storage path is twisted, and the image save node seems to be affected as well.
