### ISSUE TITLE
Random prompt in CLIPTextEncode (NSP) doesn't work anymore

### ISSUE THREAD

**Issue by zymox** [WASasquatch/was-node-suite-comfyui#404]
If I'm using a prompt like "a woman wearing a {red|green|blue} shirt" with the "CLIP Text Encode (NSP)" node, the random selection doesn't work anymore, it seems to take the prompt as is, resulting in color bleeding / multiple colored shirts. Wildcards/NSP still work fine.

It used to behave here like it still does with the ComfyUI native "CLIP Text Encode (Prompt)" node, where it selects a random text from the given list.

I'm not sure when this broke, but I'm sure that it used to work.

**Comment by WASasquatch** [comment]
Are you using a Multiline Text to feed to CLIPTextEncode? I disabled it on
that node so it can handle JSON and code for all the LLM stuff.

**Comment by zymox** [comment]
No, just simple single line text that contains both wildcards and this random list. I use this node to parse the wildcards, but now it stopped understanding the simple random list.

Any way I can re-enable it? Maybe it could be turned into a switch on the node?

**Comment by WASasquatch** [comment]
Yeah, I'll re-enable it an add a new one for raw (without it)

**Comment by WAS-PlaiLabs** [comment]
Alright, original Multiline is reverted: https://github.com/WASasquatch/was-node-suite-comfyui/commit/c258f1115dc52bc82b7c20bb5635f10cc369f62e

**Comment by zymox** [comment]
Doesn't seem to work. Your commit only seems to be about the Text Multiline node, which I'm not using.

**Comment by WASasquatch** [comment]
Ah, well CLIPTextEncode NSP should work. I haven't touched that node in well over a year.

**Comment by zymox** [comment]
Yeah, weird, but it doesn't work, at least not for me. Maybe you can verify.

Example workflow "three women wearing {red|green|blue} shirts":
![ComfyUI_01321_](https://github.com/WASasquatch/was-node-suite-comfyui/assets/18327640/84cd2e5b-09df-4c91-aaa8-d88ea944534c)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/18327640/762b31c6-cd88-4f11-bfca-9c65dda30a83)

It does work if I put the text through the Text Multiline node first so the dynamic prompts get parsed there.

**Comment by zymox** [comment]
Found the reason in the code ...
You're using the wrong brackets in your regex:

`parse_prompt = re.sub(r'\<(.*?)\>', replace_match, prompt)`

It works with <red|green|blue> instead of {red|green|blue}.

**Comment by WASasquatch** [comment]
No, that's how I do it. The `{}` are for JS, which would replace before
hitting the backend. There is usage on the readme.

**Comment by zymox** [comment]
Even in the node that you fixed a few comments above it works (and **only** works) with "{ }" so it's not exactly consistent behaviour 
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/18327640/7c145162-e991-41cc-8f04-2f40672e8314)

But whatever, I know how to use it now :) i'll close this, thanks for your time

**Comment by WASasquatch** [comment]
And you aren't using multiline text to hook up to nsp to provide the text?
What commit works prior?
