### ISSUE TITLE
Error when TensorRT is loaded for RemBG

### ISSUE THREAD

**Issue by MattRM2** [WASasquatch/was-node-suite-comfyui#413]
Hi,

I have an error when I try to use "Image Rembg" node : 
`2024-06-03 12:26:18.3178859 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************`

I have two graphics cards. One, my primary, is a GTX 1070 Ti for the display and the second one is an RTX 4070 Super for computation (3D, compositing and AI).

What I need to do to avoid this error and use the RTX 4070 Super TensorRT ? Of course, the node switch back to cuda and compute the node.

Thank you,

Matt

**Comment by bobcate** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/2823
```
pip uninstall rembg //uninstall rembg
pip uninstall onnxruntime //uninstall onnxruntime
pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
```

**Comment by MattRM2** [comment]
Thank you for your answer ;)

Matt

**Comment by bobcate** [comment]
I guess so? I launched CMD in the `..\ComfyUI\venv\Scripts` directory and called the `activate.bat`. Then I entered those lines in order.

**Comment by MattRM2** [comment]
Oki, thank you very much ;)

**Comment by 904557558** [comment]
What is your cudnn version? 
onnxruntime-gpu does not support cudnn version 9.x yet. Reducing your cudnn version to 8.9.x may solve your problem.

**Comment by MattRM2** [comment]
Hi all,

Thx for your answers, the solution of Bobcate solved my problems and another ;)
Thank you again,

Matt
