### ISSUE TITLE
Error when using the Image Levels Adjustment node

### ISSUE THREAD

**Issue by Gorislav** [WASasquatch/was-node-suite-comfyui#42]
AttributeError: 'WAS_Image_Levels' object has no attribute 'apply_image_levels/Adjustment'

I've tried different configurations and inputs, but the node always breaks the process

**Comment by WASasquatch** [comment]
Woops e0027c7ed642d53d028f462342a80190983dcab2

Should be good to go. Was up late last night (like tonight) when changing menus.

**Comment by Gorislav** [comment]
Yes, everything works!
