### ISSUE TITLE
Is there to make it compatible with py 3.9 ?

### ISSUE THREAD

**Issue by davedaverave** [WASasquatch/was-node-suite-comfyui#428]
My enviroment can't be upgraded, if there's no other way what commit should i go back to? 
THanks for the patience :)

**Comment by WASasquatch** [comment]
What are the problems you are having?

**Comment by davedaverave** [comment]
this the message in console "Cannot import /notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: cannot import name 'BlipProcessor' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)"

**Comment by WASasquatch** [comment]
Might want to take that error to Transformers since they say they support
3.8+ but is erroring for you.

**Comment by davedaverave** [comment]
I'm pasting you  the full message " Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 2398, in <module>
    from transformers import BlipProcessor, BlipForConditionalGeneration, BlipForQuestionAnswering
ImportError: cannot import name 'BlipProcessor' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)

Cannot import /notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: cannot import name 'BlipProcessor' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py) "

**Comment by WASasquatch** [comment]
Yeah the error is from Transformers, not WAS-NS. Transformers claims to be
compatible with Python 3.6+,but you are clearly having issues. You need to
report with them

**Comment by davedaverave** [comment]
I've did .. i as well noticed a different error today... Hope you don't mind


File "/notebooks/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import /notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: No module named 'numba'

Does it make sense?

**Comment by WASasquatch** [comment]
Numba should install. It was also compatible with 3.6:
https://numba.pydata.org/numba-doc/latest/user/installing.html

**Comment by davedaverave** [comment]
I've found out that the Last Ben repository for running ComfyUI on Paperspace is not being supported anymore, as the author is having issure with the platform and that's escalated making him remove the repo... 

That coud be related to the issues i was having, i will close this issue for now, until i've fount out... 
thanks a lot

**Comment by dreamlogic-X** [comment]
@davedaverave  Hey I noticed I'm having the same issue, I'm also on the Last Ben's Paperspace notebook. It's running Python 3.11.7. Wondering if you found a resolution?
