### ISSUE TITLE
CLIPTextEncode (NSP) doesn't seem to be noodling correctly in the latest update

### ISSUE THREAD

**Issue by Yggdrasil777** [WASasquatch/was-node-suite-comfyui#45]
![image](https://user-images.githubusercontent.com/775705/232113536-933db2dc-b45b-4d53-91fc-f06c2e3a4c8f.png)

`{__nationality__ __identity-female__|__monster__|__monster__ human hybrid|__rpg-class__} with __skin-color__ skin { |__skin-imperfection__| } and __body-shape__-shaped body, detailed {__color__ eyes|eyes of a __animals__}, __hair-color__ __hair-style__ with { |__hair-bangs__|__hair-braid__|__hair-texture__} and __breast-size__, wearing {__details__|transparent} {__costume-female__|__clothing-female__|__clothing__|__legwear__|__rpg-class__ armor} and {__accessory__|__accessory-hair__ in hair|__hat__ on head|__accessory-neckwear__ around neck| } and {barefoot|__footwear__}, feeling __expression__,`

results in this:
![image](https://user-images.githubusercontent.com/775705/232113743-d6bcc2e9-b771-4b86-aa0d-1709564f75c4.png)

and this:
![image](https://user-images.githubusercontent.com/775705/232114077-69a289b8-bf57-41f7-9eba-c765f7cc5bf2.png)

It used to come out like this:
`Dominican young girl with ivory skin and barrelesque-shaped body, Light steel blue eyes, blonde emo hair with reverse french braid and medium breasts, wearing maternity wear and long necklace and barefoot, feeling indifferen`t.

and this:
`Cameroonian older woman with deep Wine eyes, aqua cropped hair and flipped hair large breasts, wearing leather jacket and panama hat on head and flip flops, feeling determined.`

**Comment by WASasquatch** [comment]
I cant seem to reproduce this. It's working for me: `WAS NS CLIPTextEncode NSP: Ocean Blue Southern Hognose Snake` for `__color__ __animals__` prompt.

**Comment by Yggdrasil777** [comment]
Oh! Did it make a backup?!? I think I found the issue, sorry.  :)

**Comment by WASasquatch** [comment]
> Oh! Did it make a backup?!? I think I found the issue, sorry. :)

It doesn't by default. I just suggested it as it could be the database isn't loading, thus nothing to find to "replace".

**Comment by Yggdrasil777** [comment]
Yeah, I had to reload a backup .json I have for those wildcards. It's all good.
