### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by r7l** [WASasquatch/was-node-suite-comfyui#46]
I am using the [current version](https://github.com/comfyanonymous/ComfyUI/commit/884ea653c8d6fe19b3724f45a04a0d74cd881f2f) of Comfy. When installing your suite, i'll end up with this error:

```
WAS Node Suite Running At: /stable-diffusion/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py
WAS Node Suite Running From: /stable-diffusion/custom_nodes/was-node-suite-comfyui
WAS Node Suite: Created default conf file at `/stable-diffusion/custom_nodes/was-node-suite-comfyui/was_suite_config.json`.
Traceback (most recent call last):
  File "/stable-diffusion/nodes.py", line 1169, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/stable-diffusion/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/stable-diffusion/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 1944, in <module>
    class WAS_Load_Image_Batch:
  File "/stable-diffusion/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 1960, in WAS_Load_Image_Batch
    RETURN_TYPES = ("IMAGE",TEXT_TYPE)
NameError: name 'TEXT_TYPE' is not defined

Cannot import /stable-diffusion/custom_nodes/was-node-suite-comfyui module for custom nodes: name 'TEXT_TYPE' is not defined

```

I've installed the listed dependencies. Am i missing something else?

**Comment by WASasquatch** [comment]
Oh yeah, I see the issue there. It was only being set for already installed runs, not fresh installs. Try pulling latest commit.

**Comment by r7l** [comment]
I am running ComfyUI from inside Docker and tried to add your node suite. So it will be a fresh install everytime i'll update the image and it would actually help allot if you could provide a `requirements.txt` file. It would simplify things quite a bit.

**Comment by WASasquatch** [comment]
If I add a requirement, people may install to the wrong python and just cause issues. All dependencies are installing with ComfyUI's python environment at runtime to ensure they're accessible by ComfyUI, which for the portable version I support, is a packaged venv. For example, if someone is using portable version, and using git to install, it would be using system python to install all the dependencies.

**Comment by WASasquatch** [comment]
Went ahead and added requirements.txt anyways. We'll see how it goes for portable installs.

**Comment by r7l** [comment]
There is at least one dependency that isn't installed when installing ComfyUI requirements. I've tried without and it always ended up with an error of some broken import statement (i could look it up in detail if needed). I've just installed all of your listed dependencies and it went away. Thanks allot for the fix anyways.

**Comment by WASasquatch** [comment]
Well yeah, it's definitely needed. Lol

**Comment by r7l** [comment]
I've just tried to recreate the situation i had yesterday when no installing dependencies but the error is no longer popping up. Not sure how it came to that in the first place. Well, nevermind then and sorry for bringing it up.

**Comment by WASasquatch** [comment]
> I've just tried to recreate the situation i had yesterday when not installing dependencies but the error is no longer popping up. Not sure how it came to that in the first place. Well, nevermind then and sorry for bringing it up.

Could have been a failure in one of the dependencies own dependencies. Some of them have several dependencies of their own that install with them (or should).

**Comment by Magenta-6** [comment]
not sure if this is related.
I did an update all and now get this:
+++++++++++++++++++++++++++++++++++++++++++++++++
WAS Node Suite Error: Unable to load conf file at `E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.
++++++++++++++++++++++++++++++++++++++++++++++++

regards
