### ISSUE TITLE
[Feature request] Undo in text field for [Text Multiline] node

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [WASasquatch/was-node-suite-comfyui#460]
It would be amazing. As it is, it's so frustrating to work in the text area, since nothing can be CTRL + Z to be undone.

**Comment by WASasquatch** [comment]
You can control z in the textarea, but once you run the workflow the graph is refreshed, so it's a new DOM element technically and doesn't have that previous history. This is a ConfyUi problem.

**Comment by MNeMoNiCuZ** [comment]
Hmm, no I don't mind if I can't undo after I've run it.
Maybe it's a Firefox issue then. I cannot undo if I'm working in the text field without generations running.

**Comment by MNeMoNiCuZ** [comment]
Nevermind. Undo works, just not when you are in the text-field.
You have to click outside of the text-field to be able to undo.

The feature request was to add undo to the text-field itself when it's selected, rather than having to rely on Comfy's undo buffer.

But I get that this is not a reasonable request from this node. It should indeed be how nodes handle textareas.
