### ISSUE TITLE
WAS_Text_Load_From_File.IS_CHANGED missing?

### ISSUE THREAD

**Issue by meuter** [WASasquatch/was-node-suite-comfyui#482]
Hi,

I am using the "Load Text File" node to load a prompt from file. However, when I save the text file and rerun the prompt, the node does not seem to detect the change. I looked around at the code, and I see that in `WAS_Text_Load_Line_From_File` you added a IS_CHANGED() method that hashes the file to see if it changed:

```python
    @classmethod
    def IS_CHANGED(cls, **kwargs):
        if kwargs['mode'] != 'index':
            return float("NaN")
        else:
            m = hashlib.sha256()
            if os.path.exists(kwargs['file_path']):
                with open(kwargs['file_path'], 'rb') as f:
                    m.update(f.read())
                return m.digest().hex()
            else:
                return False
```

So locally I added a similar method to the `WAS_Text_Load_From_File` class:

```python
    @classmethod
    def IS_CHANGED(cls, **kwargs):
        m = hashlib.sha256()
        if os.path.exists(kwargs['file_path']):
            with open(kwargs['file_path'], 'rb') as f:
                m.update(f.read())
            return m.digest().hex()
        else:
            return False
```

Which seem to do the trick. Would you be interested in a PR to merge this into the code base?

Thanks for a great suite of nodes BTW ;-)

Cheers

**Comment by WASasquatch** [comment]
When not using index mode it must always run to function for file selector,
so no I wouldn't be looking for a PR. Thank you though.

**Comment by meuter** [comment]
Alright, fair enough :-)
