### ISSUE TITLE
Timecode not applying to folders in Image Save node

### ISSUE THREAD

**Issue by Fourknif** [WASasquatch/was-node-suite-comfyui#50]
When using the [time(format_code)] token to try and make dated subfolders for generations, the folders instead take the name as the text typed in rather than turning into the appropriate date. This issue is not present on images, which have converted the timecode to the appropriate time of generation.
![explorer_2023-04-19_23-02-33](https://user-images.githubusercontent.com/131326896/233247717-75061c2d-f309-4801-80d2-b5516e3ba28a.png)
![explorer_2023-04-19_23-02-46](https://user-images.githubusercontent.com/131326896/233247724-0c031cd2-e7ad-4695-a865-2347adf4331a.png)

**Comment by WASasquatch** [comment]
Right, that makes sense to have, so I went ahead and tossed that in here b023926f59d57b720f706974a710830958bf5226

**Comment by Fourknif** [comment]
Updated file comes back with this error, and the Image Save nodes now look like this and are inoperable.

![cmd_2023-04-20_11-54-1](https://user-images.githubusercontent.com/131326896/233421212-a021d659-e5d5-440b-b5d9-8a4b64f28d4c.png)
![opera_2023-04-20_11-54-24](https://user-images.githubusercontent.com/131326896/233421226-79c11e77-4a75-417d-910a-d04c6e36ef6e.png)

**Comment by WASasquatch** [comment]
No clue what that's about. I don't have that error. Did you update comfy? Looks like something weird. Why would my username and the repo commit be in a HTMl title? Lol

**Comment by Fourknif** [comment]
> There is no HTML at all in my node class so maybe you downloaded it wrong?

Seems to be the case, I had originally downloaded the updated .py file by saving linked content. Cloning the repo again has fixed the issue.
