### ISSUE TITLE
Load image batch node error

### ISSUE THREAD

**Issue by holycowdude** [WASasquatch/was-node-suite-comfyui#510]
After updating Comfui Portable and WAS Node Suite my "load image batch" has  stopped working, it worked previously in my workflow

In INDEX it says 'NaN'
When I press queue I get an error:

_Prompt outputs failed validation
Load Image Batch:
- Failed to convert an input value to a INT value: index, None, int() argument must be a string, a bytes-like object or a real number, not 'NoneType'_
- 
If I change the INDEX to a number I get an error "Index out of range"
# ComfyUI Error Report
## Error Details
- **Node ID:** 109
- **Node Type:** Load Image Batch
- **Exception Type:** IndexError
- **Exception Message:** list index out of range
## Stack Trace
```

I simply use it as a batch loader to batch process images for upscale

Please can someone help? thanks

**Comment by holycowdude** [comment]
If anyone has this problem in future, right click and select fix node

**Comment by andreszs** [comment]
Or remove-and re-add the **Logic Boolean** node.
