### ISSUE TITLE
Can't install, can't git pull on windows. Stuck around 27%.

### ISSUE THREAD

**Issue by DmytroSokhach** [WASasquatch/was-node-suite-comfyui#512]
Getting the following error around 27% while doing git pull:

> $ git clone https://github.com/WASasquatch/was-node-suite-comfyui/
> Cloning into 'was-node-suite-comfyui'...
> remote: Enumerating objects: 2320, done.
> remote: Counting objects: 100% (908/908), done.
> remote: Compressing objects: 100% (361/361), done.
> fatal: fetch-pack: invalid index-pack output | 134.00 KiB/s
> fetch-pack: unexpected disconnect while reading sideband packet
> 

Also getting

> Cloning into 'was-node-suite-comfyui'...
> remote: Enumerating objects: 2320, done.
> remote: Counting objects: 100% (896/896), done.
> remote: Compressing objects: 100% (360/360), done.
> fatal: early EOFs:  27% (646/2320), 14.15 MiB | 140.00 KiB/s
> fatal: fetch-pack: invalid index-pack output

I had this node before, but today noticed that it is not available in ComfyUI and tried to reinstall following the manual.
Any suggestions?

**Comment by WASasquatch** [comment]
See this topic on SO for possible solutions: https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed

Looks likely related to memory buffer for the pull.

**Comment by DmytroSokhach** [comment]
@WASasquatch  yeah, I've checked one, and tried couple steps from that stackoverflow before posting here. Custom Nodes Manager was my initial try, but it was constantly failing to Fix Nodes, then I deleted folder and tried git install, which didn't help.
Eventually just restarted-updated-restarted ComfyUI and Installed from Custom Nodes Manager as usual.
Up and running now 🙏

**Comment by WASasquatch** [comment]
Could have literally been weird network issues causing EOF in streams.
Strange regardless
