### ISSUE TITLE
MODELS_DIR seems to be set to ComfyUI/ComfyUI/models when server started from comfy root dir

### ISSUE THREAD

**Issue by szhublox** [WASasquatch/was-node-suite-comfyui#53]
WAS Node Suite Error: There is no write access to `/media/sd/ComfyUI/custom_nodes/was-node-suite-comfyui` or `/media/sd/ComfyUI/ComfyUI/models`. Write access is required!

`MODELS_DIR =  os.path.join(( os.getcwd()+os.sep+'ComfyUI' if not os.getcwd().startswith('/content') else os.getcwd() ), 'models')`

**Comment by WASasquatch** [comment]
The error doesn't seem to indicate that. It indicates there is no write access so it can't save models or anything.

**Comment by szhublox** [comment]
There's no write access because the directory doesn't exist. My models dir is /media/sd/ComfyUI/models but it's looking at /media/sd/ComfyUI/ComfyUI/models

**Comment by WASasquatch** [comment]
Try pull latest, using comfy paths, as I've been meaning to switch to it anyways. https://github.com/WASasquatch/was-node-suite-comfyui/commit/93d8dadb82b15c278e9a002189df6604f2a06e8b#diff-35652c7be27f406523ce77f22809c807782fa83236d30eed7d170b3859941ddbR52

**Comment by szhublox** [comment]
the complaint went away
