### ISSUE TITLE
WAS_Load_Image_Batch -> IS_CHANGED ?

### ISSUE THREAD

**Issue by MoonMoon82** [WASasquatch/was-node-suite-comfyui#54]
It seems you designed this node to reload the node, even if the input has not changed.
In WAS_Load_Image_Batch IS_CHANGED it says:
```
    @classmethod
    def IS_CHANGED(cls, **kwargs):
        return float("NaN")
```

In the usual ComfyUI LoadImage it is comparing the hash of the image to identify if it has changed.
I guess you had a good reason to design it that way, but if you have a huge input directory (>1000 files) it takes a quite long time to run the Image Batch node. Could you please check if there's a chance to adjust it, so it won't take that long to run this node anymore?

**Comment by WASasquatch** [comment]
That's has nothing to do with how long it takes (and comparing hashes would take longer), but is required otherwise the node wouldn't run at all as you haven't changed any input on the node.

**Comment by WASasquatch** [comment]
That's has nothing to do with how long it takes (and comparing hashes would take longer), but is required otherwise the node wouldn't run at all as you haven't changed any input on the node.

**Comment by polarsky89** [comment]
Also, if you could give a little bit od understanding how doeas index and batch work, so I could get some control on which image is loaded first?

**Comment by WASasquatch** [comment]
Index only works for single images, to pick a image from the batch. The list is sorted by filename, so whatever file is first in the folder will go first. Its very hacky as ComfyUI lacks crucial features like a callback function on nodes prior to a prompt run.

**Comment by WASasquatch** [comment]
You can also use the glob input to filter the files. Like `*.png` for only png files.

**Comment by polarsky89** [comment]
Thanks, that might help. 
Is it possible to implement a 'reset index' button or some method to keep the list starting from index 0 when needed? Now i figured the only method is to change the input folder to a different one, run, and then change it back. Lots of pain when trying to work with many frames in different folders

**Comment by WASasquatch** [comment]
> Thanks, that might help. Is it possible to implement a 'reset index' button or some method to keep the list starting from index 0 when needed? Now i figured the only method is to change the input folder to a different one, run, and then change it back. Lots of pain when trying to work with many frames in different folders edit: right now the index keeps going +1 until you change the folder

That somewhat falls back on lack of communication from the front end with nodes. Nodes only ever get info from the front end when they run. There needs to be a OnChange like event when input is changed it can fire off a node function that handles pre-run steps, such as resetting index, or reading a folder and populating a list to select a image instead of using a index which is hard to relate to a image. 

Comfyanonymous (or someone) needs to add this sort of functionality to ComfyUI. When a node inputs are changed we should be able to see that change on the backend to handle crucial ease of use features.

**Comment by WASasquatch** [comment]
You can also reset the `Batch Counters` by having the settings file open in notepad or whatever, and change the counter for that batch to 0. 

...
    "Batch Counters": {
        "Batch 001": 1
    },
    "Batch Paths": {
        "Batch 001": "C:\\Users\\jorda\\Pictures\\ErinKellyman"
    },
```

**Comment by WASasquatch** [comment]
> @WASasquatch I'm not quite sure if it perhaps would be sufficient to compare the index instead of comparing hashes. Maybe this would be an workaround? Just an example: I created a landscape depthmap sequence in blender (~250 files) which I input as controlnet-condition, but the same depthmap file needs to be used as controlnet condition 4 times (in 1000 batch counts). So in this case, I guess this workaround would save 3/4 of image loading time.

I don't think I'm following. Wouldn't the increment be happening in the node function itself? So it wouldn't run, to get a increment, for the IS_CHANGED to see?
