### ISSUE TITLE
Error when creating a new folder with a subfolder using Image Save node

### ISSUE THREAD

**Issue by N3-Oti** [WASasquatch/was-node-suite-comfyui#56]
I encountered an issue when using the Image Save node to create a new folder with a subfolder. When I try to create a folder with the structure '/[time(%Y-%m-%d)]/S', an error occurs, and the creation and saving process fails. However, when I attempt to create a folder with the structure '/[time(%Y-%m-%d)]', it succeeds. I believe the error occurs when trying to create a subfolder within the main folder. Could you please look into this issue?

**Comment by WASasquatch** [comment]
Please provide all errors.

**Comment by N3-Oti** [comment]
Thank you for your response. here is the error message I encountered when trying to create a nested subfolder using the Image Save Node:

WAS NS Warning: The path `./ComfyUI/output/2023-04-30/S` specified doesn't exist! Creating directory.
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\execution.py", line 184, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "J:\ComfyUI_windows_portable\ComfyUI\execution.py", line 69, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 4370, in save_images
    os.mkdir(output_path.strip())
FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: './ComfyUI/output/2023-04-30/S'

Please let me know if you need any further information or if there's anything else I can provide to help resolve this issue.

Best regards.

**Comment by WASasquatch** [comment]
Thank you. 

I will push a patch soon. In the mean time. You can get by this by replacing `os.mkdir(output_path.strip())` with `os.makedirs(output_path.strip(), exist_ok=True)` on line 4370

**Comment by WASasquatch** [comment]
This should be patched now.
