### ISSUE TITLE
SAM nodes partially broken

### ISSUE THREAD

**Issue by rvion** [WASasquatch/was-node-suite-comfyui#61]
SAM nodes are partially broken

## 🔴 downloads in the wrong folder

for vit_b, sam loader node seems to be looking in `ComfyUI\ComfyUI\models\sam` instead of `ComfyUI\models\sams` where it downloads it

## 🔴 tensor size mismatch for vit_b and vit_l

 if I fix paths manually for the Vit-B, I get things like
 
 ```
 size mismatch for image_encoder.blocks.10.mlp.lin2.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for image_encoder.blocks.11.norm1.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for image_encoder.blocks.11.norm1.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for image_encoder.blocks.11.attn.rel_pos_h: copying a param with shape torch.Size([127, 64]) from checkpoint, the shape in current model is torch.Size([27, 80]).
```

same with vit_l

## 🟢 got vit_h working with manual path fixing

**Comment by WASasquatch** [comment]
I fixed the path issues, but I am not sure about the tensor mismatch. @moorehousew do you know what this is about? I think it's the tensor to sam compatible tensor conversion, but also not sure why their models are working on different tensors for different models. Seems odd from a usage standpoint.

**Comment by Tengyang-Chen** [comment]
cause in build_sam.py
```
build_sam = build_sam_vit_h
```
It always returns vit_h, that's why only vit_h is working.
U can add some if ...else... and make `model_size` to control which one should be returned.
