### ISSUE TITLE
can not use 

### ISSUE THREAD

**Issue by LIU-ZHIHAO** [WASasquatch/was-node-suite-comfyui#65]
i am try [Recommended Installation],after restart comfyui , display error:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/24649106/236420820-3f416c84-765b-4d33-b379-3e400fc05f64.png">

**Comment by WASasquatch** [comment]
Thanks for letting me know. I replaced some quotes nones with nonetype so need to fix that condition expecting a string. You can just change the WebUI styles setting to `"None"` in the meantime.
