### ISSUE TITLE
Having trouble with wildcards (might be that I am misunderstanding where to put them)

### ISSUE THREAD

**Issue by GamingDaveUk** [WASasquatch/was-node-suite-comfyui#67]
![image](https://user-images.githubusercontent.com/131270181/236525097-40fc84e9-a78c-4098-b1c2-7f3238a25d60.png)
I have two copies of the wild card folder
F:\ComfyUI_windows_portable\ComfyUI\wildcards
and
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\wildcards

but it is not repacing the text as I would expect:
science officer, star trek, hdr, 8k, photo real __Actress__
should have __Actress__ replaced from a random line from Actress.txt in the wildcards folder
[Actress.txt](https://github.com/WASasquatch/was-node-suite-comfyui/files/11408615/Actress.txt)
![image](https://user-images.githubusercontent.com/131270181/236524740-3ed9bcdc-1a8c-42fe-a5ed-4e1ccc18db78.png)
![start_00041_](https://user-images.githubusercontent.com/131270181/236524870-0b226a95-015e-428d-8ca9-f8e653ffdac4.png)
image with workflow included as i cant share the json

**Comment by WASasquatch** [comment]
Nope. You're good, I'm just a derp and totally forgot about this node and didn't add wildcard support it. It's still working off just Noodle Soup prompts. I'll get that in. Thanks for pointing it out.

**Comment by GamingDaveUk** [comment]
> Nope. You're good, I'm just a derp and totally forgot about this node and didn't add wildcard support it. It's still working off just Noodle Soup prompts. I'll get that in. Thanks for pointing it out.
> 
> Edit: I've added support to that node [465f4d0](https://github.com/WASasquatch/was-node-suite-comfyui/commit/465f4d014e7bf64aef66c4d96474121b56881538) (plus a patch, forgot to add mode)
> 
> Go ahead and run `git pull` on it.
Will do later, cheers for fixing it chap :)

Quick question, should the wildcard folder be in:
F:\ComfyUI_windows_portable\ComfyUI\wildcards
or
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\wildcards

**Comment by WASasquatch** [comment]
> > Nope. You're good, I'm just a derp and totally forgot about this node and didn't add wildcard support it. It's still working off just Noodle Soup prompts. I'll get that in. Thanks for pointing it out.
> > Edit: I've added support to that node [465f4d0](https://github.com/WASasquatch/was-node-suite-comfyui/commit/465f4d014e7bf64aef66c4d96474121b56881538) (plus a patch, forgot to add mode)
> > Go ahead and run `git pull` on it.
> > Will do later, cheers for fixing it chap :)
> 
> Quick question, should the wildcard folder be in: F:\ComfyUI_windows_portable\ComfyUI\wildcards or F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\wildcards

WAS Node Suite path, so should be `F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\wildcards` 

You can also specifically specify the path in your `was_suite_config.json`

**Comment by GamingDaveUk** [comment]
had to redo the settings on the node but it worked great. Thankyou for the fix chap
