### ISSUE TITLE
Trouble with WAS and Docker.

### ISSUE THREAD

**Issue by PassiveLemon** [WASasquatch/was-node-suite-comfyui#69]
Currently, I am working on getting a somewhat modular loading system for nodes in the Docker implementation of ComfyUI [here](https://github.com/AbdBarho/stable-diffusion-webui-docker). Any directory in the custom_nodes location will get scanned for a requirements.txt and will be installed through pip.

I am using the WAS suite as a test since it seems like a good place to start. The pip install part seems to be fine but ComfyUI will not start with WAS. It will return the error:
```
webui-docker-comfy-1  | python: can't open file '/data/config/comfy/custom_nodes/was-node-suite-comfyui/main.py': [Errno 2] No such file or directory
webui-docker-comfy-1 exited with code 2
```
I'm not quite sure what is happening since I don't know python and I don't see a main.py file in this repository.

I have made sure to give permissions to the entire custom_nodes directory and its subdirectories/files.

Maybe you know what's going on here?

**Comment by WASasquatch** [comment]
I haven't really used docker so I am not sure if it is related or not. But from the looks of it the script you are using is trying to load a main.py, which naturally doesn't exist. WAS Suite isn't a stand alone program so it doesn't have a main execution point.

**Comment by PassiveLemon** [comment]
Quite coincidentally, it turns out that the mounting for the paths in the container were simply just broken. Someone had already made a PR to fix it, it just wasn't merged yet. It was merged today and it works without me needing to change anything.
