### ISSUE TITLE
[Feature Request]: ControlNet Tile with MultiDiffusion/Tiled Diffusion

### ISSUE THREAD

**Issue by paulo-coronado** [WASasquatch/was-node-suite-comfyui#71]
Hello! I think it would be great to have an implementation for the ControlNet Tile model, specifically incorporating the MultiDiffusion technique. This addition could greatly enhance our control and upscaling/enhancing capabilities. I'm eager to hear your thoughts on this and I would be very happy to collaborate on it as well!

**Comment by WASasquatch** [comment]
If I am not mistaken, this could be supported out the box if Comfyanonymous upgraded his control net code? Or does it need something special? I haven't used control net too much in ComfyUI, just awhile back in A1111

**Comment by paulo-coronado** [comment]
Hum, not really... Fannovel developed a Tile Preprocessor, but the implementation isn't correct, because the Tiled Diffusion requires an overlapping tile splitting and KSample process on each tile, not that simple... 😅

I am developing a [KSampleTiled node](https://github.com/paulo-coronado/comfy_tiled_diffusion) that applies the [Tiled Diffusion method](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111). It still on progress, but let's see how it evolves! :)
