### ISSUE TITLE
How to loop through all items in a wildcard file?

### ISSUE THREAD

**Issue by roygear** [WASasquatch/was-node-suite-comfyui#73]
The default behavior is choosing items randomly. Does the " Loop through all items " logic exist?

**Comment by WASasquatch** [comment]
Like sequentially getting first through last wildcare in each prompt? It would require making use of settings file and storing temp values to know where it's at. Unfortunately the node classes aren't ran one and then their functions ran, whole class is instantiated fresh every prompt run, which makes development wonky.

**Comment by roygear** [comment]
Thanks for your answer.
Can I request a functionality like "Batch load text file"?
Thanks.

**Comment by WASasquatch** [comment]
> Thanks for your answer. Can I request a functionality like "Batch load text file"? Thanks.

Added it to my list of TODO

**Comment by WASasquatch** [comment]
Added a sequential line text loader: https://github.com/WASasquatch/was-node-suite-comfyui/commit/41cea6016962c15fa002cbf96e0a4d1d02fa1a2a
