### ISSUE TITLE
dlib installation error, cloned comfui, win11

### ISSUE THREAD

**Issue by johnyboro** [WASasquatch/was-node-suite-comfyui#74]
after running:
pip install -r requirements.txt

I get this error:
Installing collected packages: dlib, threadpoolctl, smmap, numpy, joblib, img2texture, pythonperlin, pilgram, gitdb, face_recognition, transformers, scikit-learn, gitpython, fairscale
  DEPRECATION: dlib is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for dlib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      C:\Program Files\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext

      ERROR: CMake must be installed to build dlib

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by WASasquatch** [comment]
You need [cmake](https://cmake.org/download/) for windows. 

Also more help here: https://github.com/ageitgey/face_recognition/issues/1401
