### ISSUE TITLE
Image Paste Crop by location - feathering buggy

### ISSUE THREAD

**Issue by pennyvc** [WASasquatch/was-node-suite-comfyui#80]
The crop blending does not seem to want to hit zero at the edges, it will leave fine lines unless it is set extremely low to the point of uselessness.
The crop blend also does so on all sides even if it is at the border edge of the image it is being pasted into which causes issues if you want to paste an image in a corner or on an edge.

Im not actually a coder or anything so its hard for me to explain what is happening, so here's an example image and nodegraph Im messing with, I could easily just be implementing it wrong maybe, but it feels like it shouldn't be doing what it does.

[splitupscaletest.txt](https://github.com/WASasquatch/was-node-suite-comfyui/files/11524239/splitupscaletest.txt)
![ComfyUI_00937_](https://github.com/WASasquatch/was-node-suite-comfyui/assets/128430314/0a56dc9e-ce36-4755-8b4a-dc941fad38d7) - you can see the fine lines near the monsters head where I have overlaid an image to show how its creating a fine line where one should probably not exist around it.

**Comment by WASasquatch** [comment]
No I see what you mean, and I thought I fixed this. Not the border edges by the boundary edges in general. The way it works is the square shrinks as you apply more blur so that the actual blurring shouldn't hit the edge of the crop (so parts of the blue get cut off). But apparently that isn't working as I thought it was.

**Comment by WASasquatch** [comment]
Alright I rebuilt the function for side detection.

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/01bdd763-7b08-41c0-9693-c54856de3f03)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/48932794-e24a-40ad-a04a-f73ad3c8cf04)

**Comment by pennyvc** [comment]
Ahh thankye, :D

**Comment by pennyvc** [comment]
hmmm, more strangeness, it doesnt like crops that are against eachother, and seems to be a little inconsistant with it.
not sure how i'd handle it, a checkbox merge edges maybe?
also 2 output images but only one functions on those nodes.
![Captur999e](https://github.com/WASasquatch/was-node-suite-comfyui/assets/128430314/5fa41ef2-0d17-4808-9c55-ba0fdcc818e3)
![Capkij9ture](https://github.com/WASasquatch/was-node-suite-comfyui/assets/128430314/71e5f94d-c5a3-4cc5-a18f-66b15bb6c748)

**Comment by WASasquatch** [comment]
I'm not good with math. I may just revert to old method. Too much of a hassle.
