### ISSUE TITLE
Latent Size to Number doesn't work

### ISSUE THREAD

**Issue by Bocian-1** [WASasquatch/was-node-suite-comfyui#83]
Always outputs 64 in both width and height.
Image Size to Number is fine

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/70019596/77f19330-58fa-47ee-af9a-e254884bcd49)

Also as a side note:
When using the logic switches, all nodes before it get executed even if their output is not passed through the switch. For example, if I wanted to create an on/off switch for something like face restoration, even in the off-state, all these nodes still are executed, wasting a significant amount of time.
On the contrary, a simple switch using ComfyUI's reroute nodes where you choose the output by reconnecting the nodes works just fine and none of the nodes that remain unused are ever executed:
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/70019596/fbfbf4dd-c25b-4bdf-8c4a-fb007be05354)
This, however, lacks the versatility of being able to control multiple such switches with a single logic boolean that your nodes offer.
Wouldn't it be possible to emulate a reroute switch switching connections based on the logic boolean to get the best of both worlds?

Edit: found a typo in Image Remove Background (Alpha) node: output is named 'iamges' instead if 'images'

**Comment by Bocian-1** [comment]
Oh, so the size is actually different in latent space? My bad for assuming otherwise then. I thought I used a similar node before and it did output the same size as normal, but checking with a different one now it's as you say so I must be remembering things wrong.

Just for clarification with the on/off thing I meant a structure like this:
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/70019596/f6a997d8-0abe-4b8f-9422-8fe88851c760)
So in this example, it's one input (image), and a bunch of nodes for processing it and outputting the processed image. The switch just decides whether the output of the whole structure is the processed or unprocessed input.

No worries though, I figured it would probably be an issue with ComfyUI itself, but couldn't help asking just in case. 

Great thanks for clarifying things for me. And also for putting in all the work to make the custom nodes. I really cannot overstate how helpful they are.

**Comment by WASasquatch** [comment]
Well if it is just two image inputs it should switch to either or based on 0/1 boolean input. So either input or result. But yeah I can't tell upstream not to actually do the processing up to that point which is annoying, especially when it is a huge post processing tree.
