### ISSUE TITLE
bug: number operations with greater-than or equals throws error

### ISSUE THREAD

**Issue by dereekb** [WASasquatch/was-node-suite-comfyui#85]
When using the output as a boolean, the following error is thrown in console:

```
Traceback (most recent call last):
  File "/stable-diffusion/execution.py", line 184, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "/stable-diffusion/execution.py", line 60, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "/stable-diffusion/execution.py", line 70, in recursive_execute
    if "ui" in outputs[unique_id]:
TypeError: argument of type 'float' is not iterable
```

Input types don't matter. Doesn't throw an error when using greater-than.

Also, there's a typo for this option. (equels)

![error](https://github.com/WASasquatch/was-node-suite-comfyui/assets/3586580/8b22b4d5-33ff-4fb4-bee5-cd82f3f24dce)

Example:

[greaterthanerror.zip](https://github.com/WASasquatch/was-node-suite-comfyui/files/11631028/greaterthanerror.zip)

Workaround:

Use greater than and adjust the inputs accordingly.

**Comment by WASasquatch** [comment]
Oh yep, that's the issue. "equels", so it was default to output number_a, but number_a wasn't being output as a tuple. Thanks for catching that honestly lol. Should be patched now.

**Comment by dereekb** [comment]
Great, thanks for patching that quickly! I was making a tangled mess of nodes earlier and suddenly got that error.

I think there's another bug with the Number Input Condition Switch too and the values it outputs when using greater-than. Instead of return true/false as 0/1 it was returning the greater of the value or something like that. I'll reproduce it when I get a chance and post it here.

**Comment by WASasquatch** [comment]
Hmm, yeah let me know if you see something. I don't see any issues with it at a glance

```python
        if comparison:
            if comparison == 'greater-than':
                result = number_a if number_a > number_b else number_b
            elif comparison == 'greater-than or equals':
                result = number_a if number_a >= number_b else number_b
            elif comparison == 'less-than':
                result = number_a if number_a < number_b else number_b
            elif comparison == 'less-than or equals':
                result = number_a if number_a <= number_b else number_b
            elif comparison == 'equals':
                result = number_a if number_a == number_b else number_b
            elif comparison == 'does not equal':
                result = number_a if number_a != number_b else number_b
            elif comparison == 'divisible by':
                result = number_a if number_b % number_a == 0 else number_b
            elif comparison == 'if A odd':
                result = number_a if number_a % 2 != 0 else number_b
            elif comparison == 'if A even':
                result = number_a if number_a % 2 == 0 else number_b
            elif comparison == 'if A prime':
                result = number_a if self.is_prime(number_a) else number_b
            elif comparison == 'factor of':
                result = number_a if number_b % number_a == 0 else number_b
            else:
                result = number_a
```

**Comment by WASasquatch** [comment]
Has it been corrected on your end?

**Comment by dereekb** [comment]
I don't know if it's by design, but I originally expected the Number Input Condition to return a boolean value instead of the larger of the two values (Max Value functionality).

I guess the Number Input Condition functions all work like that though where either A or B is returned based on the code above. Aside from my initial confusion yep it works great, thanks! I've been running through most of the nodes in your library and if I find any more bugs I'll make a new issue.

**Comment by WASasquatch** [comment]
> I didn't know it was by design, but I originally expected the Number Input Condition to return a boolean value instead of the larger of the two values (Max Value functionality).
> 
> I guess the Number Input Condition functions all work like that though where either A or B is returned based on the code above. Aside from my initial confusion yep it works great, thanks! I've been running through most of the nodes in your library and if I find any more bugs I'll make a new issue.

That is a good point though, so: https://github.com/WASasquatch/was-node-suite-comfyui/commit/391adf9b24b0ce8f78a612729a3cfb55c3c7bb54

**Comment by dereekb** [comment]
Thanks! Some other functions I might suggest is AND / OR / etc, with any non-zero number acting as true. Right now I've gotta pipe some different nodes together to achieve some of those and sometimes it isn't as clear as a single input that read "if A and B" or "if A or B"

**Comment by WASasquatch** [comment]
I'm not sure how that'd work? ComfyUI always requires an output. So can't really do a "A or B" cause they both would contain something and be "True". Additionally "A and B" assumes a computation that A or B is resulting in True with?

**Comment by dereekb** [comment]
Something like:

```
if comparison == 'and':
                result = number_a if number_a > 0 and number_b > 0 else number_b
elif comparison == 'or':
                result = number_a if number_a > 0 or number_b > 0 else number_b
```

I am not brushed up on python syntax so that might not be right. Here's what I'm thinking in JS:

```
if (comparison === 'if A and B') {
   return (a > 0 && b > 0) ? a : b;
} else if (comparison === 'if A or B') {
   return (a > 0 || b >0 ) ? a : b;
} else if (comparison === 'if A nor B') {
   return (a === 0 && b === 0 ) ? a : b;
}
```

Of course also taking respect to the "return a boolean" result.
