### ISSUE TITLE
width and height around the wrong way

### ISSUE THREAD

**Issue by pennyvc** [WASasquatch/was-node-suite-comfyui#86]
Perlin noise node and maybe more have width and height around the wrong way.

additionally, generate background gradient suffers a similar problem with horizontal and verticall mislabeled

**Comment by WASasquatch** [comment]
Seem to be working fine. You sure about that? Cause I'm not sure what you're talking about. 

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/c5460ef7-eb02-4191-ac4c-c3e4d83f4750)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/0762391d-f680-44c8-af73-bbdc6064e59f)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/cdd10af2-3134-4473-a0eb-92f741dd7576)

**Comment by pennyvc** [comment]
mysterious o.0 ill look into it lol because its definitely buggy on my end

**Comment by WASasquatch** [comment]
Still working as expected...

![Screenshot_17](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/7e324952-4e10-4ed1-98e6-dd03283014ee)
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/0618b0d4-7931-4895-b99f-855e20d056b9)

The blend nodes don't resize images, so if you aren't sizing them right, strange things will happen:

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/4d2ef0e5-f335-4471-99a8-0f19b1b5d458)

**Comment by pennyvc** [comment]
found it, bugs fixed, issue with python install somehow was doing it >.> numba was bugging but not actually erroring until I did a restart then it wouldn't load was anymore. I have no idea how that happened and my coder friend is mystified lol 
i had him have a look to see what was wrong and he's like, nope its fine. your computers magical.  *sadface* soo we spent like a couple of hours hunting down the problem lol   - your fine, all me >.>

**Comment by WASasquatch** [comment]
Ohh, ok! Yeah I kept looking at the code completely mistified too. I was just like "I can't see anything! There our FOUR LIGHTS!" (star trek reference)

**Comment by pennyvc** [comment]
now, captain picard, i have a question for you... how many lights do you see?  def one of the good eps.

nahh, should be good now, friend sorted it all, lucky i have a housemate who is my pet coder lol, or id still be insisting there are four lights!
