### ISSUE TITLE
[Bug?] Image Stitch behavior 

### ISSUE THREAD

**Issue by bmad4ever** [WASasquatch/was-node-suite-comfyui#89]
It appears the stitching to the right is not behaving correctly for the example below. 
Stitching to the left seems to be working fine after swapping the inputs, so it can be used instead.

I did not look at the implementation to know if this is viable, but under the supposition that "left stitch" is always working as intended, maybe the image inputs can be swapped when stitching "to the right" to fix the current behavior?

![stitch](https://github.com/WASasquatch/was-node-suite-comfyui/assets/9298668/935564ee-b391-48c5-9475-6abafc5f673e)

**Comment by bmad4ever** [comment]
Bizarre, I can't seem to get it to work right, and updated the local repo copy today before doing this. Maybe I'm not understanding the intended behavior?

If is not too much to ask, can you check if the following example is working as intended? (the image contains the workflow)

Kind regards.


![rightStitch](https://github.com/WASasquatch/was-node-suite-comfyui/assets/9298668/fb4b3535-1792-4eba-b02b-952bd2aa4deb)

**Comment by WASasquatch** [comment]
I think I figured it out...

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/2dd32323-5b30-4f0d-9711-2858d8f9cd41)
