### ISSUE TITLE
[feature request] Allow widgets on number nodes

### ISSUE THREAD

**Issue by melMass** [WASasquatch/was-node-suite-comfyui#94]
Hey,

Thanks for the suite, I learned a lot about comfy by browsing it.
I'm having a small qol suggestion: allow widgets instead of inputs for numbers!

Here for instance I don't "want" to have to place a `Primitive` or `ConstantNumber`
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/7041726/ff0ee801-ed77-44a1-9eaf-803a01ee03af)

The menu to toggle between inputs and widget doesn't work on them, only the operation can be switched:
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/7041726/39ac9c5c-d980-409f-a4a1-60fb5ce5ab7a)

Thanks

**Comment by WASasquatch** [comment]
Then everyone using logic and stuff would have to convert input fields to node inputs to use them. It wouldn't  make sense for something like a number operation to have hardset input on the node itself. How would that be dynamic?

**Comment by melMass** [comment]
> It wouldn't make sense for something like a number operation to have hardset input on the node itself. How would that be dynamic?

IMO it does, you don't need both A & B to be dynamic in many instances.

> One of the biggest issues with the NUMBER type is that it is universal and ComfyUI enforces types. These can be float or int, and ComfyUI won't know what to use in either case.

I haven't checked the internals before opening the issue but I'm guessing the type isn't enforced while in the `NUMBER` space no?
Like it's a loose `number` type like in js.

Let's say I want to divide by two a dynamic input having to use extra nodes feels unnecessary, but if you don't see benefits from this feel free to close the issue.

**Comment by WASasquatch** [comment]
> > It wouldn't make sense for something like a number operation to have hardset input on the node itself. How would that be dynamic?
> 
> IMO it does, you don't need both A & B to be dynamic in many instances.
> 
> > One of the biggest issues with the NUMBER type is that it is universal and ComfyUI enforces types. These can be float or int, and ComfyUI won't know what to use in either case.
> 
> I haven't checked the internals before opening the issue but I'm guessing the type isn't enforced while in the `NUMBER` space no? Like it's a loose `number` type like in js.
> 
> Let's say I want to divide by two a dynamic input having to use extra nodes feels unnecessary, but if you don't see benefits from this feel free to close the issue.

But if you are just dividing non-inputs you are manually inputting yourself, you could just put the division result in a primitive and do the math yourself since these aren't inputs that you may not know the current result of.
