### ISSUE TITLE
Speed up BLIP?

### ISSUE THREAD

**Issue by MoonMoon82** [WASasquatch/was-node-suite-comfyui#95]
I'm using the BLIP node to get more accurat text for image segmentation. It seems that everytime the BLIP node is being executed the model is loaded into memory. Is there a way speed this up?
Maybe separate model loading and executing in different nodes?

**Comment by WASasquatch** [comment]
I could probably do that, yeah. I personally like things loading and unloading so I can do massive images though. That's the logic I deployed with WAS-NS

**Comment by WASasquatch** [comment]
I'll add a optional `BLIP_MODEL` input which will override creation of the model in the analyze node.

**Comment by WASasquatch** [comment]
Alright, there is the **BLIP Model Loader** node that you can feed as an optional input tot he BLIP analyze node. 

Similarly MiDaS Depth Approx has a MiDaS Model Loader node now too.

**Comment by MoonMoon82** [comment]
Thank you very much! It boosted my workflow from ~60sec to ~26sec !

**Comment by MoonMoon82** [comment]
@WASasquatch Just curious.. wouldn't it also speed up workflows if the CLIPSeg Masking Node also gets a separate Model Loading node?

**Comment by WASasquatch** [comment]
Added optional CLIPSeg Model Loader. Also exposed the model string, in case there ever is other models to use.

**Comment by MoonMoon82** [comment]
@WASasquatch thx! I just tested it! Works great!
