### ISSUE TITLE
Issue with Face Repair Workflow in ComfyUI: Offset Issue in Paste Face Step

### ISSUE THREAD

**Issue by lcolok** [WASasquatch/was-node-suite-comfyui#97]
Dear developers,

First and foremost, I would like to express my sincere gratitude for your work on the ComfyUI project. It has been a valuable tool for me in my workflow.

I am currently attempting to reproduce the facial repair workflow using ComfyUI that you have demonstrated. However, I have encountered an issue where the "Paste face" step results in some offset. The repaired face does not align correctly with its original position.
<img width="1276" alt="Snipaste_2023-06-23_04-15-54" src="https://github.com/WASasquatch/was-node-suite-comfyui/assets/33664979/8d6c55ec-dbed-4c3e-965c-bd877f4c8ab5">
Unfortunately, due to the sensitive nature of the CROP DATA, I am unable to print the results using the debug console tool in WAS (WebAssembly Studio). As a result, I am unable to identify the specific stage at which the error occurs.

Could you kindly assist me in examining this matter? I would greatly appreciate any guidance or insights you can provide.

For your reference, I have attached the JSON file for the workflow, which corresponds to the metadata of the image in question:
https://i.postimg.cc/3xyYTrdc/FC-Fix-Face-Crop-Node.png

Thank you once again for your remarkable efforts in developing ComfyUI. I look forward to your kind assistance.

Best regards

**Comment by WASasquatch** [comment]
I think that workflow is outdated, the inputs have been swapped around I believe. Could you try deleting and remaking the crop and paste nodes?

**Comment by WASasquatch** [comment]
Oh, I see the issue. That should be patched now.

**Comment by WASasquatch** [comment]
Also, you may be interested in the CLIPSeg Face Fix method:
![CLIPSeg_Face_Crop_Fix](https://github.com/WASasquatch/was-node-suite-comfyui/assets/1151589/236c7742-32c2-4f7d-902f-7d321beee840)
