### ISSUE TITLE
How can I use the cache?

### ISSUE THREAD

**Issue by zhs007** [WASasquatch/was-node-suite-comfyui#99]
Can you give me an example?

**Comment by WASasquatch** [comment]
It's very limited. You just give it a name, and save it. Then you can load it via that name with the load cache. It probably should handle a full path instead of filenames.

**Comment by zhs007** [comment]
However, when I read it and connect it to another node, after run it, it will notice a 'invalid node' message box, I have tested 3 types of cache.

**Comment by WASasquatch** [comment]
You can only cache the 3 types it allows, Image, Latent, and Conditioning. I've updated these nodes to allow for full path and filename suffix (which is actually prefix but forgot to rename)
